#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS_Code
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="pimpTest_Data")]
	public partial class GlobalDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertGlobal_User_Audit(Global_User_Audit instance);
    partial void UpdateGlobal_User_Audit(Global_User_Audit instance);
    partial void DeleteGlobal_User_Audit(Global_User_Audit instance);
    partial void InsertGlobal_Sitemap(Global_Sitemap instance);
    partial void UpdateGlobal_Sitemap(Global_Sitemap instance);
    partial void DeleteGlobal_Sitemap(Global_Sitemap instance);
    partial void InsertGlobal_Data_Capture(Global_Data_Capture instance);
    partial void UpdateGlobal_Data_Capture(Global_Data_Capture instance);
    partial void DeleteGlobal_Data_Capture(Global_Data_Capture instance);
    partial void InsertGlobal_Errors_Log(Global_Errors_Log instance);
    partial void UpdateGlobal_Errors_Log(Global_Errors_Log instance);
    partial void DeleteGlobal_Errors_Log(Global_Errors_Log instance);
    #endregion
		
		public GlobalDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["pimpTest_DataConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public GlobalDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public GlobalDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public GlobalDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public GlobalDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Global_User_Audit> Global_User_Audits
		{
			get
			{
				return this.GetTable<Global_User_Audit>();
			}
		}
		
		public System.Data.Linq.Table<Global_Sitemap> Global_Sitemaps
		{
			get
			{
				return this.GetTable<Global_Sitemap>();
			}
		}
		
		public System.Data.Linq.Table<Global_Data_Capture> Global_Data_Captures
		{
			get
			{
				return this.GetTable<Global_Data_Capture>();
			}
		}
		
		public System.Data.Linq.Table<Global_Errors_Log> Global_Errors_Logs
		{
			get
			{
				return this.GetTable<Global_Errors_Log>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Global_User_Audit")]
	public partial class Global_User_Audit : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _uid;
		
		private System.Nullable<System.Guid> _ApplicationId;
		
		private System.Nullable<System.Guid> _User_ID;
		
		private string _IP_Address;
		
		private string _Browser_String;
		
		private string _Current_URL;
		
		private string _Previous_URL;
		
		private string _Auth_User;
		
		private System.Nullable<System.DateTime> _DateTime;
		
		private string _Current_User_Path;
		
		private string _AnonymousID;
		
		private string _Remote_User;
		
		private string _Logon_User;
		
		private string _HTTP_Host;
		
		private string _Windows_Platform;
		
		private System.Nullable<int> _JavaScript;
		
		private System.Nullable<int> _Win16;
		
		private System.Nullable<int> _Win32;
		
		private string _BrowserScreen_Resolution;
		
		private System.Nullable<int> _ActiveXControls;
		
		private System.Nullable<int> _IsMobile;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnuidChanging(int value);
    partial void OnuidChanged();
    partial void OnApplicationIdChanging(System.Nullable<System.Guid> value);
    partial void OnApplicationIdChanged();
    partial void OnUser_IDChanging(System.Nullable<System.Guid> value);
    partial void OnUser_IDChanged();
    partial void OnIP_AddressChanging(string value);
    partial void OnIP_AddressChanged();
    partial void OnBrowser_StringChanging(string value);
    partial void OnBrowser_StringChanged();
    partial void OnCurrent_URLChanging(string value);
    partial void OnCurrent_URLChanged();
    partial void OnPrevious_URLChanging(string value);
    partial void OnPrevious_URLChanged();
    partial void OnAuth_UserChanging(string value);
    partial void OnAuth_UserChanged();
    partial void OnDateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnDateTimeChanged();
    partial void OnCurrent_User_PathChanging(string value);
    partial void OnCurrent_User_PathChanged();
    partial void OnAnonymousIDChanging(string value);
    partial void OnAnonymousIDChanged();
    partial void OnRemote_UserChanging(string value);
    partial void OnRemote_UserChanged();
    partial void OnLogon_UserChanging(string value);
    partial void OnLogon_UserChanged();
    partial void OnHTTP_HostChanging(string value);
    partial void OnHTTP_HostChanged();
    partial void OnWindows_PlatformChanging(string value);
    partial void OnWindows_PlatformChanged();
    partial void OnJavaScriptChanging(System.Nullable<int> value);
    partial void OnJavaScriptChanged();
    partial void OnWin16Changing(System.Nullable<int> value);
    partial void OnWin16Changed();
    partial void OnWin32Changing(System.Nullable<int> value);
    partial void OnWin32Changed();
    partial void OnBrowserScreen_ResolutionChanging(string value);
    partial void OnBrowserScreen_ResolutionChanged();
    partial void OnActiveXControlsChanging(System.Nullable<int> value);
    partial void OnActiveXControlsChanged();
    partial void OnIsMobileChanging(System.Nullable<int> value);
    partial void OnIsMobileChanged();
    #endregion
		
		public Global_User_Audit()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uid", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int uid
		{
			get
			{
				return this._uid;
			}
			set
			{
				if ((this._uid != value))
				{
					this.OnuidChanging(value);
					this.SendPropertyChanging();
					this._uid = value;
					this.SendPropertyChanged("uid");
					this.OnuidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApplicationId", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> ApplicationId
		{
			get
			{
				return this._ApplicationId;
			}
			set
			{
				if ((this._ApplicationId != value))
				{
					this.OnApplicationIdChanging(value);
					this.SendPropertyChanging();
					this._ApplicationId = value;
					this.SendPropertyChanged("ApplicationId");
					this.OnApplicationIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_ID", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> User_ID
		{
			get
			{
				return this._User_ID;
			}
			set
			{
				if ((this._User_ID != value))
				{
					this.OnUser_IDChanging(value);
					this.SendPropertyChanging();
					this._User_ID = value;
					this.SendPropertyChanged("User_ID");
					this.OnUser_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IP_Address", DbType="VarChar(50)")]
		public string IP_Address
		{
			get
			{
				return this._IP_Address;
			}
			set
			{
				if ((this._IP_Address != value))
				{
					this.OnIP_AddressChanging(value);
					this.SendPropertyChanging();
					this._IP_Address = value;
					this.SendPropertyChanged("IP_Address");
					this.OnIP_AddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Browser_String", DbType="VarChar(255)")]
		public string Browser_String
		{
			get
			{
				return this._Browser_String;
			}
			set
			{
				if ((this._Browser_String != value))
				{
					this.OnBrowser_StringChanging(value);
					this.SendPropertyChanging();
					this._Browser_String = value;
					this.SendPropertyChanged("Browser_String");
					this.OnBrowser_StringChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Current_URL", DbType="VarChar(255)")]
		public string Current_URL
		{
			get
			{
				return this._Current_URL;
			}
			set
			{
				if ((this._Current_URL != value))
				{
					this.OnCurrent_URLChanging(value);
					this.SendPropertyChanging();
					this._Current_URL = value;
					this.SendPropertyChanged("Current_URL");
					this.OnCurrent_URLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Previous_URL", DbType="VarChar(255)")]
		public string Previous_URL
		{
			get
			{
				return this._Previous_URL;
			}
			set
			{
				if ((this._Previous_URL != value))
				{
					this.OnPrevious_URLChanging(value);
					this.SendPropertyChanging();
					this._Previous_URL = value;
					this.SendPropertyChanged("Previous_URL");
					this.OnPrevious_URLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Auth_User", DbType="VarChar(255)")]
		public string Auth_User
		{
			get
			{
				return this._Auth_User;
			}
			set
			{
				if ((this._Auth_User != value))
				{
					this.OnAuth_UserChanging(value);
					this.SendPropertyChanging();
					this._Auth_User = value;
					this.SendPropertyChanged("Auth_User");
					this.OnAuth_UserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateTime
		{
			get
			{
				return this._DateTime;
			}
			set
			{
				if ((this._DateTime != value))
				{
					this.OnDateTimeChanging(value);
					this.SendPropertyChanging();
					this._DateTime = value;
					this.SendPropertyChanged("DateTime");
					this.OnDateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Current_User_Path", DbType="VarChar(255)")]
		public string Current_User_Path
		{
			get
			{
				return this._Current_User_Path;
			}
			set
			{
				if ((this._Current_User_Path != value))
				{
					this.OnCurrent_User_PathChanging(value);
					this.SendPropertyChanging();
					this._Current_User_Path = value;
					this.SendPropertyChanged("Current_User_Path");
					this.OnCurrent_User_PathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnonymousID", DbType="VarChar(255)")]
		public string AnonymousID
		{
			get
			{
				return this._AnonymousID;
			}
			set
			{
				if ((this._AnonymousID != value))
				{
					this.OnAnonymousIDChanging(value);
					this.SendPropertyChanging();
					this._AnonymousID = value;
					this.SendPropertyChanged("AnonymousID");
					this.OnAnonymousIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remote_User", DbType="VarChar(255)")]
		public string Remote_User
		{
			get
			{
				return this._Remote_User;
			}
			set
			{
				if ((this._Remote_User != value))
				{
					this.OnRemote_UserChanging(value);
					this.SendPropertyChanging();
					this._Remote_User = value;
					this.SendPropertyChanged("Remote_User");
					this.OnRemote_UserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Logon_User", DbType="VarChar(50)")]
		public string Logon_User
		{
			get
			{
				return this._Logon_User;
			}
			set
			{
				if ((this._Logon_User != value))
				{
					this.OnLogon_UserChanging(value);
					this.SendPropertyChanging();
					this._Logon_User = value;
					this.SendPropertyChanged("Logon_User");
					this.OnLogon_UserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HTTP_Host", DbType="VarChar(255)")]
		public string HTTP_Host
		{
			get
			{
				return this._HTTP_Host;
			}
			set
			{
				if ((this._HTTP_Host != value))
				{
					this.OnHTTP_HostChanging(value);
					this.SendPropertyChanging();
					this._HTTP_Host = value;
					this.SendPropertyChanged("HTTP_Host");
					this.OnHTTP_HostChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Windows_Platform", DbType="VarChar(50)")]
		public string Windows_Platform
		{
			get
			{
				return this._Windows_Platform;
			}
			set
			{
				if ((this._Windows_Platform != value))
				{
					this.OnWindows_PlatformChanging(value);
					this.SendPropertyChanging();
					this._Windows_Platform = value;
					this.SendPropertyChanged("Windows_Platform");
					this.OnWindows_PlatformChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JavaScript", DbType="Int")]
		public System.Nullable<int> JavaScript
		{
			get
			{
				return this._JavaScript;
			}
			set
			{
				if ((this._JavaScript != value))
				{
					this.OnJavaScriptChanging(value);
					this.SendPropertyChanging();
					this._JavaScript = value;
					this.SendPropertyChanged("JavaScript");
					this.OnJavaScriptChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Win16", DbType="Int")]
		public System.Nullable<int> Win16
		{
			get
			{
				return this._Win16;
			}
			set
			{
				if ((this._Win16 != value))
				{
					this.OnWin16Changing(value);
					this.SendPropertyChanging();
					this._Win16 = value;
					this.SendPropertyChanged("Win16");
					this.OnWin16Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Win32", DbType="Int")]
		public System.Nullable<int> Win32
		{
			get
			{
				return this._Win32;
			}
			set
			{
				if ((this._Win32 != value))
				{
					this.OnWin32Changing(value);
					this.SendPropertyChanging();
					this._Win32 = value;
					this.SendPropertyChanged("Win32");
					this.OnWin32Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BrowserScreen_Resolution", DbType="Char(10)")]
		public string BrowserScreen_Resolution
		{
			get
			{
				return this._BrowserScreen_Resolution;
			}
			set
			{
				if ((this._BrowserScreen_Resolution != value))
				{
					this.OnBrowserScreen_ResolutionChanging(value);
					this.SendPropertyChanging();
					this._BrowserScreen_Resolution = value;
					this.SendPropertyChanged("BrowserScreen_Resolution");
					this.OnBrowserScreen_ResolutionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActiveXControls", DbType="Int")]
		public System.Nullable<int> ActiveXControls
		{
			get
			{
				return this._ActiveXControls;
			}
			set
			{
				if ((this._ActiveXControls != value))
				{
					this.OnActiveXControlsChanging(value);
					this.SendPropertyChanging();
					this._ActiveXControls = value;
					this.SendPropertyChanged("ActiveXControls");
					this.OnActiveXControlsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsMobile", DbType="Int")]
		public System.Nullable<int> IsMobile
		{
			get
			{
				return this._IsMobile;
			}
			set
			{
				if ((this._IsMobile != value))
				{
					this.OnIsMobileChanging(value);
					this.SendPropertyChanging();
					this._IsMobile = value;
					this.SendPropertyChanged("IsMobile");
					this.OnIsMobileChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Global_Sitemap")]
	public partial class Global_Sitemap : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _uid;
		
		private System.Nullable<System.Guid> _Application_Id;
		
		private string _url;
		
		private System.DateTime _lastmod;
		
		private string _changefreq;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnuidChanging(int value);
    partial void OnuidChanged();
    partial void OnApplication_IdChanging(System.Nullable<System.Guid> value);
    partial void OnApplication_IdChanged();
    partial void OnurlChanging(string value);
    partial void OnurlChanged();
    partial void OnlastmodChanging(System.DateTime value);
    partial void OnlastmodChanged();
    partial void OnchangefreqChanging(string value);
    partial void OnchangefreqChanged();
    #endregion
		
		public Global_Sitemap()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uid", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int uid
		{
			get
			{
				return this._uid;
			}
			set
			{
				if ((this._uid != value))
				{
					this.OnuidChanging(value);
					this.SendPropertyChanging();
					this._uid = value;
					this.SendPropertyChanged("uid");
					this.OnuidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Application_Id", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> Application_Id
		{
			get
			{
				return this._Application_Id;
			}
			set
			{
				if ((this._Application_Id != value))
				{
					this.OnApplication_IdChanging(value);
					this.SendPropertyChanging();
					this._Application_Id = value;
					this.SendPropertyChanged("Application_Id");
					this.OnApplication_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_url", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string url
		{
			get
			{
				return this._url;
			}
			set
			{
				if ((this._url != value))
				{
					this.OnurlChanging(value);
					this.SendPropertyChanging();
					this._url = value;
					this.SendPropertyChanged("url");
					this.OnurlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastmod", DbType="DateTime NOT NULL")]
		public System.DateTime lastmod
		{
			get
			{
				return this._lastmod;
			}
			set
			{
				if ((this._lastmod != value))
				{
					this.OnlastmodChanging(value);
					this.SendPropertyChanging();
					this._lastmod = value;
					this.SendPropertyChanged("lastmod");
					this.OnlastmodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_changefreq", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string changefreq
		{
			get
			{
				return this._changefreq;
			}
			set
			{
				if ((this._changefreq != value))
				{
					this.OnchangefreqChanging(value);
					this.SendPropertyChanging();
					this._changefreq = value;
					this.SendPropertyChanged("changefreq");
					this.OnchangefreqChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Global_Data_Capture")]
	public partial class Global_Data_Capture : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _uid;
		
		private string _Raw_Data;
		
		private System.Nullable<System.Guid> _Application_Id;
		
		private System.Guid _User_ID;
		
		private System.DateTime _date_time;
		
		private string _Failed_At;
		
		private int _Reviewed;
		
		private System.Nullable<System.DateTime> _Reviewed_By_DateTime;
		
		private System.Nullable<System.Guid> _Reviewed_By_UserID;
		
		private string _Version;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnuidChanging(int value);
    partial void OnuidChanged();
    partial void OnRaw_DataChanging(string value);
    partial void OnRaw_DataChanged();
    partial void OnApplication_IdChanging(System.Nullable<System.Guid> value);
    partial void OnApplication_IdChanged();
    partial void OnUser_IDChanging(System.Guid value);
    partial void OnUser_IDChanged();
    partial void Ondate_timeChanging(System.DateTime value);
    partial void Ondate_timeChanged();
    partial void OnFailed_AtChanging(string value);
    partial void OnFailed_AtChanged();
    partial void OnReviewedChanging(int value);
    partial void OnReviewedChanged();
    partial void OnReviewed_By_DateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnReviewed_By_DateTimeChanged();
    partial void OnReviewed_By_UserIDChanging(System.Nullable<System.Guid> value);
    partial void OnReviewed_By_UserIDChanged();
    partial void OnVersionChanging(string value);
    partial void OnVersionChanged();
    #endregion
		
		public Global_Data_Capture()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uid", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int uid
		{
			get
			{
				return this._uid;
			}
			set
			{
				if ((this._uid != value))
				{
					this.OnuidChanging(value);
					this.SendPropertyChanging();
					this._uid = value;
					this.SendPropertyChanged("uid");
					this.OnuidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Raw_Data", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Raw_Data
		{
			get
			{
				return this._Raw_Data;
			}
			set
			{
				if ((this._Raw_Data != value))
				{
					this.OnRaw_DataChanging(value);
					this.SendPropertyChanging();
					this._Raw_Data = value;
					this.SendPropertyChanged("Raw_Data");
					this.OnRaw_DataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Application_Id", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> Application_Id
		{
			get
			{
				return this._Application_Id;
			}
			set
			{
				if ((this._Application_Id != value))
				{
					this.OnApplication_IdChanging(value);
					this.SendPropertyChanging();
					this._Application_Id = value;
					this.SendPropertyChanged("Application_Id");
					this.OnApplication_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_ID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid User_ID
		{
			get
			{
				return this._User_ID;
			}
			set
			{
				if ((this._User_ID != value))
				{
					this.OnUser_IDChanging(value);
					this.SendPropertyChanging();
					this._User_ID = value;
					this.SendPropertyChanged("User_ID");
					this.OnUser_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date_time", DbType="DateTime NOT NULL")]
		public System.DateTime date_time
		{
			get
			{
				return this._date_time;
			}
			set
			{
				if ((this._date_time != value))
				{
					this.Ondate_timeChanging(value);
					this.SendPropertyChanging();
					this._date_time = value;
					this.SendPropertyChanged("date_time");
					this.Ondate_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Failed_At", DbType="VarChar(50)")]
		public string Failed_At
		{
			get
			{
				return this._Failed_At;
			}
			set
			{
				if ((this._Failed_At != value))
				{
					this.OnFailed_AtChanging(value);
					this.SendPropertyChanging();
					this._Failed_At = value;
					this.SendPropertyChanged("Failed_At");
					this.OnFailed_AtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reviewed", DbType="Int NOT NULL")]
		public int Reviewed
		{
			get
			{
				return this._Reviewed;
			}
			set
			{
				if ((this._Reviewed != value))
				{
					this.OnReviewedChanging(value);
					this.SendPropertyChanging();
					this._Reviewed = value;
					this.SendPropertyChanged("Reviewed");
					this.OnReviewedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reviewed_By_DateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> Reviewed_By_DateTime
		{
			get
			{
				return this._Reviewed_By_DateTime;
			}
			set
			{
				if ((this._Reviewed_By_DateTime != value))
				{
					this.OnReviewed_By_DateTimeChanging(value);
					this.SendPropertyChanging();
					this._Reviewed_By_DateTime = value;
					this.SendPropertyChanged("Reviewed_By_DateTime");
					this.OnReviewed_By_DateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reviewed_By_UserID", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> Reviewed_By_UserID
		{
			get
			{
				return this._Reviewed_By_UserID;
			}
			set
			{
				if ((this._Reviewed_By_UserID != value))
				{
					this.OnReviewed_By_UserIDChanging(value);
					this.SendPropertyChanging();
					this._Reviewed_By_UserID = value;
					this.SendPropertyChanged("Reviewed_By_UserID");
					this.OnReviewed_By_UserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Version", DbType="VarChar(15)")]
		public string Version
		{
			get
			{
				return this._Version;
			}
			set
			{
				if ((this._Version != value))
				{
					this.OnVersionChanging(value);
					this.SendPropertyChanging();
					this._Version = value;
					this.SendPropertyChanged("Version");
					this.OnVersionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Global_Errors_Log")]
	public partial class Global_Errors_Log : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _uid;
		
		private System.Nullable<System.Guid> _Application_Id;
		
		private System.Nullable<System.Guid> _User_ID;
		
		private string _User_Email;
		
		private string _Load_Date;
		
		private string _Error_Message;
		
		private string _Error_Previous_URL;
		
		private string _Error_URL;
		
		private string _Error_Target;
		
		private string _Error_Source;
		
		private string _Trace_Error;
		
		private string _Error_Trace;
		
		private string _Last_Exception;
		
		private string _Session_Data;
		
		private string _Version;
		
		private System.Nullable<System.DateTime> _Date_Time;
		
		private int _Reviewed;
		
		private string _Domain;
		
		private string _Error_Url_Path;
		
		private string _Error_Url_QS;
		
		private string _Error_Previous_Url_Path;
		
		private string _Error_Previous_Url_QS;
		
		private string _AdditionalInformation;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnuidChanging(int value);
    partial void OnuidChanged();
    partial void OnApplication_IdChanging(System.Nullable<System.Guid> value);
    partial void OnApplication_IdChanged();
    partial void OnUser_IDChanging(System.Nullable<System.Guid> value);
    partial void OnUser_IDChanged();
    partial void OnUser_EmailChanging(string value);
    partial void OnUser_EmailChanged();
    partial void OnLoad_DateChanging(string value);
    partial void OnLoad_DateChanged();
    partial void OnError_MessageChanging(string value);
    partial void OnError_MessageChanged();
    partial void OnError_Previous_URLChanging(string value);
    partial void OnError_Previous_URLChanged();
    partial void OnError_URLChanging(string value);
    partial void OnError_URLChanged();
    partial void OnError_TargetChanging(string value);
    partial void OnError_TargetChanged();
    partial void OnError_SourceChanging(string value);
    partial void OnError_SourceChanged();
    partial void OnTrace_ErrorChanging(string value);
    partial void OnTrace_ErrorChanged();
    partial void OnError_TraceChanging(string value);
    partial void OnError_TraceChanged();
    partial void OnLast_ExceptionChanging(string value);
    partial void OnLast_ExceptionChanged();
    partial void OnSession_DataChanging(string value);
    partial void OnSession_DataChanged();
    partial void OnVersionChanging(string value);
    partial void OnVersionChanged();
    partial void OnDate_TimeChanging(System.Nullable<System.DateTime> value);
    partial void OnDate_TimeChanged();
    partial void OnReviewedChanging(int value);
    partial void OnReviewedChanged();
    partial void OnDomainChanging(string value);
    partial void OnDomainChanged();
    partial void OnError_Url_PathChanging(string value);
    partial void OnError_Url_PathChanged();
    partial void OnError_Url_QSChanging(string value);
    partial void OnError_Url_QSChanged();
    partial void OnError_Previous_Url_PathChanging(string value);
    partial void OnError_Previous_Url_PathChanged();
    partial void OnError_Previous_Url_QSChanging(string value);
    partial void OnError_Previous_Url_QSChanged();
    partial void OnAdditionalInformationChanging(string value);
    partial void OnAdditionalInformationChanged();
    #endregion
		
		public Global_Errors_Log()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uid", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int uid
		{
			get
			{
				return this._uid;
			}
			set
			{
				if ((this._uid != value))
				{
					this.OnuidChanging(value);
					this.SendPropertyChanging();
					this._uid = value;
					this.SendPropertyChanged("uid");
					this.OnuidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Application_Id", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> Application_Id
		{
			get
			{
				return this._Application_Id;
			}
			set
			{
				if ((this._Application_Id != value))
				{
					this.OnApplication_IdChanging(value);
					this.SendPropertyChanging();
					this._Application_Id = value;
					this.SendPropertyChanged("Application_Id");
					this.OnApplication_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_ID", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> User_ID
		{
			get
			{
				return this._User_ID;
			}
			set
			{
				if ((this._User_ID != value))
				{
					this.OnUser_IDChanging(value);
					this.SendPropertyChanging();
					this._User_ID = value;
					this.SendPropertyChanged("User_ID");
					this.OnUser_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_Email", DbType="VarChar(50)")]
		public string User_Email
		{
			get
			{
				return this._User_Email;
			}
			set
			{
				if ((this._User_Email != value))
				{
					this.OnUser_EmailChanging(value);
					this.SendPropertyChanging();
					this._User_Email = value;
					this.SendPropertyChanged("User_Email");
					this.OnUser_EmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Load_Date", DbType="VarChar(50)")]
		public string Load_Date
		{
			get
			{
				return this._Load_Date;
			}
			set
			{
				if ((this._Load_Date != value))
				{
					this.OnLoad_DateChanging(value);
					this.SendPropertyChanging();
					this._Load_Date = value;
					this.SendPropertyChanged("Load_Date");
					this.OnLoad_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Error_Message", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Error_Message
		{
			get
			{
				return this._Error_Message;
			}
			set
			{
				if ((this._Error_Message != value))
				{
					this.OnError_MessageChanging(value);
					this.SendPropertyChanging();
					this._Error_Message = value;
					this.SendPropertyChanged("Error_Message");
					this.OnError_MessageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Error_Previous_URL", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Error_Previous_URL
		{
			get
			{
				return this._Error_Previous_URL;
			}
			set
			{
				if ((this._Error_Previous_URL != value))
				{
					this.OnError_Previous_URLChanging(value);
					this.SendPropertyChanging();
					this._Error_Previous_URL = value;
					this.SendPropertyChanged("Error_Previous_URL");
					this.OnError_Previous_URLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Error_URL", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Error_URL
		{
			get
			{
				return this._Error_URL;
			}
			set
			{
				if ((this._Error_URL != value))
				{
					this.OnError_URLChanging(value);
					this.SendPropertyChanging();
					this._Error_URL = value;
					this.SendPropertyChanged("Error_URL");
					this.OnError_URLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Error_Target", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Error_Target
		{
			get
			{
				return this._Error_Target;
			}
			set
			{
				if ((this._Error_Target != value))
				{
					this.OnError_TargetChanging(value);
					this.SendPropertyChanging();
					this._Error_Target = value;
					this.SendPropertyChanged("Error_Target");
					this.OnError_TargetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Error_Source", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Error_Source
		{
			get
			{
				return this._Error_Source;
			}
			set
			{
				if ((this._Error_Source != value))
				{
					this.OnError_SourceChanging(value);
					this.SendPropertyChanging();
					this._Error_Source = value;
					this.SendPropertyChanged("Error_Source");
					this.OnError_SourceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trace_Error", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Trace_Error
		{
			get
			{
				return this._Trace_Error;
			}
			set
			{
				if ((this._Trace_Error != value))
				{
					this.OnTrace_ErrorChanging(value);
					this.SendPropertyChanging();
					this._Trace_Error = value;
					this.SendPropertyChanged("Trace_Error");
					this.OnTrace_ErrorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Error_Trace", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Error_Trace
		{
			get
			{
				return this._Error_Trace;
			}
			set
			{
				if ((this._Error_Trace != value))
				{
					this.OnError_TraceChanging(value);
					this.SendPropertyChanging();
					this._Error_Trace = value;
					this.SendPropertyChanged("Error_Trace");
					this.OnError_TraceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Last_Exception", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Last_Exception
		{
			get
			{
				return this._Last_Exception;
			}
			set
			{
				if ((this._Last_Exception != value))
				{
					this.OnLast_ExceptionChanging(value);
					this.SendPropertyChanging();
					this._Last_Exception = value;
					this.SendPropertyChanged("Last_Exception");
					this.OnLast_ExceptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Session_Data", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Session_Data
		{
			get
			{
				return this._Session_Data;
			}
			set
			{
				if ((this._Session_Data != value))
				{
					this.OnSession_DataChanging(value);
					this.SendPropertyChanging();
					this._Session_Data = value;
					this.SendPropertyChanged("Session_Data");
					this.OnSession_DataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Version", DbType="VarChar(15)")]
		public string Version
		{
			get
			{
				return this._Version;
			}
			set
			{
				if ((this._Version != value))
				{
					this.OnVersionChanging(value);
					this.SendPropertyChanging();
					this._Version = value;
					this.SendPropertyChanged("Version");
					this.OnVersionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date_Time", DbType="DateTime")]
		public System.Nullable<System.DateTime> Date_Time
		{
			get
			{
				return this._Date_Time;
			}
			set
			{
				if ((this._Date_Time != value))
				{
					this.OnDate_TimeChanging(value);
					this.SendPropertyChanging();
					this._Date_Time = value;
					this.SendPropertyChanged("Date_Time");
					this.OnDate_TimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reviewed", DbType="Int NOT NULL")]
		public int Reviewed
		{
			get
			{
				return this._Reviewed;
			}
			set
			{
				if ((this._Reviewed != value))
				{
					this.OnReviewedChanging(value);
					this.SendPropertyChanging();
					this._Reviewed = value;
					this.SendPropertyChanged("Reviewed");
					this.OnReviewedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Domain", DbType="NVarChar(MAX)")]
		public string Domain
		{
			get
			{
				return this._Domain;
			}
			set
			{
				if ((this._Domain != value))
				{
					this.OnDomainChanging(value);
					this.SendPropertyChanging();
					this._Domain = value;
					this.SendPropertyChanged("Domain");
					this.OnDomainChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Error_Url_Path", DbType="NVarChar(MAX)")]
		public string Error_Url_Path
		{
			get
			{
				return this._Error_Url_Path;
			}
			set
			{
				if ((this._Error_Url_Path != value))
				{
					this.OnError_Url_PathChanging(value);
					this.SendPropertyChanging();
					this._Error_Url_Path = value;
					this.SendPropertyChanged("Error_Url_Path");
					this.OnError_Url_PathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Error_Url_QS", DbType="NVarChar(MAX)")]
		public string Error_Url_QS
		{
			get
			{
				return this._Error_Url_QS;
			}
			set
			{
				if ((this._Error_Url_QS != value))
				{
					this.OnError_Url_QSChanging(value);
					this.SendPropertyChanging();
					this._Error_Url_QS = value;
					this.SendPropertyChanged("Error_Url_QS");
					this.OnError_Url_QSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Error_Previous_Url_Path", DbType="NVarChar(MAX)")]
		public string Error_Previous_Url_Path
		{
			get
			{
				return this._Error_Previous_Url_Path;
			}
			set
			{
				if ((this._Error_Previous_Url_Path != value))
				{
					this.OnError_Previous_Url_PathChanging(value);
					this.SendPropertyChanging();
					this._Error_Previous_Url_Path = value;
					this.SendPropertyChanged("Error_Previous_Url_Path");
					this.OnError_Previous_Url_PathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Error_Previous_Url_QS", DbType="NVarChar(MAX)")]
		public string Error_Previous_Url_QS
		{
			get
			{
				return this._Error_Previous_Url_QS;
			}
			set
			{
				if ((this._Error_Previous_Url_QS != value))
				{
					this.OnError_Previous_Url_QSChanging(value);
					this.SendPropertyChanging();
					this._Error_Previous_Url_QS = value;
					this.SendPropertyChanged("Error_Previous_Url_QS");
					this.OnError_Previous_Url_QSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdditionalInformation", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string AdditionalInformation
		{
			get
			{
				return this._AdditionalInformation;
			}
			set
			{
				if ((this._AdditionalInformation != value))
				{
					this.OnAdditionalInformationChanging(value);
					this.SendPropertyChanging();
					this._AdditionalInformation = value;
					this.SendPropertyChanged("AdditionalInformation");
					this.OnAdditionalInformationChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
