(function(){
var e=true,g=null,h=false,i=navigator,aa=undefined,ba=encodeURIComponent,k=parseInt,l=window,n=document,o=Math;function ca(a,b){return a.toString=b}var q="push",r="toString",s="valueOf",t="length",da="plugins",u="prototype",ea="round",v="slice",w="replace",x="document",y="split",fa="cookie",ga="charAt",A="userAgent",B="screen",C="indexOf",ha="domain",E="write",F="call",ia="random",G="getParameter",ja="referrer",H="substring",ka="apply",la="contentWindow",I="getTime",J="join",ma="toLowerCase";
n.URL&&(n.URL[C]("?google_debug")>0||n.URL[C]("&google_debug")>0);function na(a,b){var c=parseFloat(a);return isNaN(c)||c>1||c<0?b:c};var oa="pagead2.googlesyndication.com",pa="pubads.g.doubleclick.net",qa="partner.googleadservices.com",ra=oa,sa=pa,ta=qa;var ua={google_ad_channel:"channel",google_ad_host:"host",google_ad_host_channel:"h_ch",google_ad_host_tier_id:"ht_id",google_ad_region:"region",google_ad_section:"region",google_ad_type:"ad_type",google_adtest:"adtest",google_allow_expandable_ads:"ea",google_alternate_ad_url:"alternate_ad_url",google_alternate_color:"alt_color",google_bid:"bid",google_city:"gcs",google_color_bg:"color_bg",google_color_border:"color_border",google_color_line:"color_line",google_color_link:"color_link",google_color_text:"color_text",
google_color_url:"color_url",google_contents:"contents",google_country:"gl",google_cust_age:"cust_age",google_cust_ch:"cust_ch",google_cust_gender:"cust_gender",google_cust_id:"cust_id",google_cust_interests:"cust_interests",google_cust_job:"cust_job",google_cust_l:"cust_l",google_cust_lh:"cust_lh",google_cust_u_url:"cust_u_url",google_disable_video_autoplay:"disable_video_autoplay",google_ed:"ed",google_encoding:"oe",google_feedback:"feedback_link",google_flash_version:"flash",google_font_face:"f",
google_gl:"gl",google_hints:"hints",google_kw:"kw",google_kw_type:"kw_type",google_language:"hl",google_page_url:"url",google_referrer_url:"ref",google_region:"gr",google_reuse_colors:"reuse_colors",google_safe:"adsafe",google_tag_info:"gut",google_targeting:"targeting",google_ui_features:"ui",google_ui_version:"uiv",google_video_doc_id:"video_doc_id",google_video_product_type:"video_product_type"},va={google_ad_format:"format",google_ad_output:"output",google_ad_callback:"callback",google_ad_height:"h",
google_ad_override:"google_ad_override",google_ad_slot:"slotname",google_ad_width:"w",google_analytics_uacct:"ga_wpids",google_correlator:"correlator",google_cpa_choice:"cpa_choice",google_ctr_threshold:"ctr_t",google_image_size:"image_size",google_last_modified_time:"lmt",google_max_num_ads:"num_ads",google_max_radlink_len:"max_radlink_len",google_num_radlinks:"num_radlinks",google_num_radlinks_per_unit:"num_radlinks_per_unit",google_only_ads_with_video:"only_ads_with_video",google_page_location:"loc",
google_rl_dest_url:"rl_dest_url",google_rl_filtering:"rl_filtering",google_rl_mode:"rl_mode",google_rt:"rt",google_skip:"skip"},wa={google_only_pyv_ads:"pyv"};function K(a){return typeof ba=="function"?ba(a):escape(a)}function xa(a){if(a in ya)return ya[a];return ya[a]=i[A][ma]()[C](a)!=-1}var ya={};function za(){return xa("msie")&&!l.opera}
function Aa(){if(i[da]&&i.mimeTypes[t]){var a=i[da]["Shockwave Flash"];if(a&&a.description)return a.description[w](/([a-zA-Z]|\s)+/,"")[w](/(\s)+r/,".")}else if(i[A]&&i[A][C]("Windows CE")>=0){for(var b=3,c=1;c;)try{c=new ActiveXObject("ShockwaveFlash.ShockwaveFlash."+(b+1));b++}catch(d){c=g}return b[r]()}else if(za()){c=g;try{c=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.7")}catch(f){b=0;try{c=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.6");b=6;c.AllowScriptAccess="always"}catch(j){if(b==
6)return b[r]()}try{c=new ActiveXObject("ShockwaveFlash.ShockwaveFlash")}catch(m){}}if(c){b=c.GetVariable("$version")[y](" ")[1];return b[w](/,/g,".")}}return"0"};function Ba(a,b,c,d){this._value_=a;this._expires_=b;this._path_=c;this._domain_=d;if(!this._path_)this._path_="/";if(this._domain_==g)this._domain_=n[ha]}ca(Ba[u],function(){return"[GA_GoogleCookieInfo: value="+this._value_+", expires="+this._expires_+", path="+this._path_+"]"});function L(){this.F=this.ib();this.ca=h;if(!this.F)this.ca=this.Ca()}L[u].$="__gads=";L[u].M="GoogleAdServingTest=";L[u].setCookieInfo=function(a){this.w=a._cookies_[0];if(this.w!=g){this.F=this.w._value_;this.qb()}};L[u].ea=function(a){var b=(new Date)[s](),c=new Date;c.setTime(b+a);return c};L[u].Ma=function(){var a=15552000000,b=this.ea(a),c="ID=12345:T="+a,d="/",f=n[ha];return new Ba(c,b[s](),d,f)};var Ca="http://"+ta+"/gampad/cookie.js?callback=_GA_googleCookieHelper.setCookieInfo";
L[u].Fa=function(a){if(!(this.F||!this.ca)){var b="script",c=n[ha],d=Ca+"&client="+K(a)+"&domain="+K(c);n[E]("<"+b+' src="'+d+'"></'+b+">")}};L[u].Ca=function(){n.cookie=this.M+"Good";var a=this.na(this.M),b=a=="Good";if(b){var c=this.ea(-1);n.cookie=this.M+"; expires="+c.toGMTString()}return b};L[u].ib=function(){var a=this.na(this.$);return a};L[u].na=function(a){var b=n[fa],c=b[C](a),d="";if(c!=-1){var f=c+a[t],j=b[C](";",f);if(j==-1)j=b[t];d=b[H](f,j)}return d};
L[u].qb=function(){if(!(this.w==g))if(this.F){var a=new Date;a.setTime(1000*this.w._expires_);var b=this.w._domain_,c=this.$+this.F+"; expires="+a.toGMTString()+"; path="+this.w._path_+"; domain=."+b;n.cookie=c}};function Ia(a,b){try{return a.top[x].URL==b.URL}catch(c){}return h};var Ja=this,Ka=function(a,b,c){var d=a[y]("."),f=c||Ja;!(d[0]in f)&&f.execScript&&f.execScript("var "+d[0]);for(var j;d[t]&&(j=d.shift());)if(!d[t]&&b!==aa)f[j]=b;else f=f[j]?f[j]:(f[j]={})};o.floor(o[ia]()*2147483648)[r](36);
var La=function(a,b){var c=a.rb;if(arguments[t]>2){var d=Array[u][v][F](arguments,2);c&&d.unshift[ka](d,c);c=d}b=a.tb||b;a=a.sb||a;var f,j=b||Ja;f=c?function(){var m=Array[u][v][F](arguments);m.unshift[ka](m,c);return a[ka](j,m)}:function(){return a[ka](j,arguments)};f.rb=c;f.tb=b;f.sb=a;return f},M=function(a,b,c){Ka(a,b,c)},Ma=function(a,b){function c(){}c.prototype=b[u];a.Fb=b[u];a.prototype=new c};var Na=n,O=i,P=l;
function Oa(){var a=Na[fa],b=o[ea]((new Date)[I]()/1000),c=P.google_analytics_domain_name,d=typeof c=="undefined"?Pa("auto"):Pa(c),f=a[C]("__utma="+d+".")>-1,j=a[C]("__utmb="+d)>-1,m=a[C]("__utmc="+d)>-1,p,z={},D=!!P&&!!P.gaGlobal;if(f){p=a[y]("__utma="+d+".")[1][y](";")[0][y](".");z.sid=j&&m?p[3]+"":D&&P.gaGlobal.sid?P.gaGlobal.sid:b+"";z.vid=p[0]+"."+p[1];z.from_cookie=e}else{z.sid=D&&P.gaGlobal.sid?P.gaGlobal.sid:b+"";z.vid=D&&P.gaGlobal.vid?P.gaGlobal.vid:(o[ea](o[ia]()*2147483647)^Qa()&2147483647)+
"."+b;z.from_cookie=h}z.dh=d;z.hid=D&&P.gaGlobal.hid?P.gaGlobal.hid:o[ea](o[ia]()*2147483647);return P.gaGlobal=z}function Qa(){var a=Na[fa]?Na[fa]:"",b=P.history[t],c,d,f=[O.appName,O.version,O.language?O.language:O.browserLanguage,O.platform,O[A],O.javaEnabled()?1:0][J]("");if(P[B])f+=P[B].width+"x"+P[B].height+P[B].colorDepth;else if(P.java){d=java.awt.Toolkit.getDefaultToolkit().getScreenSize();f+=d[B].width+"x"+d[B].height}f+=a;f+=Na[ja]?Na[ja]:"";for(c=f[t];b>0;)f+=b--^c++;return Ra(f)}
function Ra(a){var b=1,c=0,d,f;if(!(a==aa||a=="")){b=0;for(d=a[t]-1;d>=0;d--){f=a.charCodeAt(d);b=(b<<6&268435455)+f+(f<<14);c=b&266338304;b=c!=0?b^c>>21:b}}return b}function Pa(a){if(!a||a==""||a=="none")return 1;if("auto"==a){a=Na[ha];if("www."==a[H](0,4))a=a[H](4,a[t])}return Ra(a[ma]())};var Ta=o[ia]()<na("0.005",0.0010)&&l.GA_jstiming&&l.GA_jstiming.load&&l.location.protocol=="http:";if(Ta){var Q=l.GA_jstiming.load;Q.tick("js_load")}function R(a){return typeof a=="function"}function Ua(a,b){if(typeof a!="string"||a[t]==0)return g;else if(typeof b!="string"||b[t]==0)return g;return S().aa(a,b)}M("GA_googleAddSlot",Ua);function _GA_googleInitializeAdEngine(a){if(!T()){Va(Wa(a));T().initialize()}}M("_GA_googleInitializeAdEngine",_GA_googleInitializeAdEngine);
function Xa(){S().vb=e;_GA_googleInitializeAdEngine(g);var a=T().j;a=="sync"||a=="sync_sra"?T().l():S().Ha()}M("GA_googleFetchAds",Xa);function Ya(){_GA_googleInitializeAdEngine("iframe");l._GA_googleCookieHelper.Fa(l.GS_googleGetIdsForAdSenseService())}M("GA_googleUseIframeRendering",Ya);function Za(){var a=l.GA_googleEnv[G]("google_ad_impl");a==g&&l.GA_googleEnv.setParameter("google_ad_impl","sync_sra")}M("GA_googleUseSyncSRARendering",Za);
function $a(a){if(!(T()==g))if(!(T().j=="iframe")){if(T().K)if(T().Z){var b=S().u(a);if(b==g)return;else if(!b._enabled_)return}else return;else if(T().z(a)!=g&&!T().n)return;T().q(a)}}M("GA_googleFillSlot",$a);function ab(a,b,c,d){a=a||"";b=b||"";c=c||0;d=d||0;if(!(T()==g))if(!(T().j!="iframe")){S().aa(a,b);var f=new bb(c,d,h,e);S().ua(b,f);T().q(b)}}M("GA_googleFillSlotWithSize",ab);function cb(){db(new U(ua));Va(g)}M("GA_googleResetAll",cb);l.google_noFetch=h;function eb(){l.google_noFetch=e}
M("GA_googleNoFetch",eb);function fb(){l.google_delayFetch=e}M("GA_googleDelayFetch",fb);function bb(a,b,c,d){this._width_=a;this._height_=b;this._expandable_=c;this._enabled_=d}ca(bb[u],function(){return"[GA_GoogleAdSlotAttr: width="+this._width_+", height="+this._height_+", expandable="+this._expandable_+", enabled="+this._enabled_+"]"});
function gb(a){for(var b={},c=a[y]("?"),d=c[c[t]-1][y]("&"),f=0;f<d[t];f++){var j=d[f][y]("=");if(j[0])try{b[j[0][ma]()]=j[t]>1?l.decodeURIComponent?decodeURIComponent(j[1][w](hb," ")):unescape(j[1]):""}catch(m){}}return b}function ib(a){var b=a||n.URL;this.gb=gb(b)}ib[u].getParameter=function(a){return a==g?g:this.gb[a]};ib[u].setParameter=function(a,b){this.gb[a]=b};function jb(a){return a[w](/&/g,"&amp;")[w](/</g,"&lt;")[w](/>/g,"&gt;")[w](/\"/g,"&quot;")}
function kb(){this.P=g;this.hb=h;this.Eb=(new Date)[s]()}
kb[u].za=function(a){if(!(this.P!=g))if(!this.hb)if(this.P=l.open("","GoogleAdCapture","width=1100, height=1400, status=no, resizable=yes, scrollbars=yes,menubar=yes, toolbar=yes")){var b=this.P[x],c=[];c[q]('<html>\n<head>\n<title>Google Ad Capture Window</title>\n<script>function displayTime(id, start){var delta=(new Date()).valueOf() - start;document.getElementById(id).innerHTML=""+delta;}var pageStartTime = (new Date()).valueOf();var slotStartTime = 0;window.onload=function(){displayTime("total", pageStartTime);};<\/script></head>\n<body>\n');c[q]("<p>Google Ad Capture Window</p>");
for(var d in a)R(a[d])||c[q](this.pb(d,a[d]));c[q]("<p>Time blocked rendering ads (ms): <label id='blocked'></label>");c[q]("<script>displayTime('blocked', pageStartTime);<\/script>");c[q]("<p>Total Page Load Time (ms): <label id='total'></label>");c[q]("</body>\n</html>");var f=c[J]("\n"),j=l.GA_googleEnv[G]("google_capture_norender")!=g;j?b[E](jb(f)):b[E](f);b.close()}else this.hb=e};
kb[u].pb=function(a,b){var c="<script>slotStartTime = (new Date()).valueOf();<\/script>",d="<p>Slot "+a+"</p>",f;f=b==g||b._html_==g?"No ad":b._html_;var j="<p>Slot Time (ms): <label id='"+a+"'></label>",m='<script>displayTime("'+a+'", slotStartTime);<\/script>';return c+d+"\n"+f+"\n"+j+m};function W(a){this.f={};this.O=a}W[u].$a=function(a){return a in this.O};W[u].N=function(a,b,c){if(a){b||(b="");if(this.$a(a))if((c=typeof c=="undefined"||c)||!this.f[a])this.f[a]=b}};
W[u].eb=function(a){for(var b in a.f)R(a.f[b])||this.f[b]||(this.f[b]=a.f[b])};W[u].getAttribute=function(a){return this.f[a]};W[u].i=function(){var a=[];for(var b in this.f)if(!R(this.f[b]))if(!(b=="google_gl"&&this.f.google_country!=g)){var c=ua[b]||va[b]||wa[b]||g,d=this.f[b];c&&d&&a[q](c+"="+K(d))}return a[J]("&")};
var mb=function(a,b,c,d){var f=lb(a,b,c,d),j=[];f[0]&&f[0][t]>0&&j[q](f[0][J]("&"));f[1]&&f[1][t]>0&&j[q]("sps="+f[1][J]("|"));return j[J]("&")},lb=function(a,b,c,d){var f=[],j=[],m=b.f;for(var p in d)if(!R(p)){var z=d[p];if(z){var D="";if(m[p]!=g)D=K(m[p]);var N=[],V=-1,Da=-1;for(var Ea in a)if(!R(a[Ea])){++V;if(c[Ea]==g)N[q]("");else{var Sa=c[Ea].f;if(Sa[p]!=g){N[q](K(K(Sa[p])));Da=V}else N[q]("")}}if(Da>=0){var wb=K(D),Fa=[];Fa[q](wb);for(var Ga=0;Ga<=Da;++Ga)Fa[q](N[Ga]);j[q](z+","+Fa[J](","))}else D&&
f[q](z+"="+D)}}var Ha=[];Ha[q](f);Ha[q](j);return Ha};function nb(a,b){this.X=a;this.C=b;this.pa=0;this.Bb=this.da=this.ia=h;this.zb=this.Ab=this.Ga=this.wb=g}nb[u].oa=function(){this.da=e;this.wb=(new Date)[s]()};nb[u].mb=function(){this.Ga=(new Date)[s]()};nb[u].ob=function(){this.Bb=e;this.Ab=(new Date)[s]()};nb[u].nb=function(){this.zb=(new Date)[s]()};ca(nb[u],function(){return"[GA_GoogleAdSlot: pubid="+this.X+", name="+this.C+", loaded="+this.ia+", tries="+this.pa+"]"});
function U(a){this.b={};this.g=[];this.B={};this.O=a;this.W=new W(this.O);this.L={};this.vb=h;this.r=g}U[u].aa=function(a,b){var c=new nb(a,b);return this.b[c.C]=c};U[u].ha=function(a){var b=[];for(var c in this.b)if(!R(this.b[c])){if(a){var d=this.u(c);if(d==g||!d._enabled_)continue}var f=this.b[c];f.da||b[q](f)}return b};U[u].Ua=function(a){return this.ha(a)[t]};U[u].Qa=function(){var a=[];for(var b in this.b){var c=this.b[b];R(c)||c.da&&c.Ga==g&&a[q](b)}return a};
U[u].Ta=function(){var a=0;for(var b in this.b)if(!R(this.b[b])){var c=this.u(b);c!=g&&c._enabled_&&a++}return a};U[u].ma=function(){for(var a in this.b)if(!R(this.b[a])){var b=this.b[a];b.oa()}};U[u].la=function(a){var b=this.b[a];b.oa()};U[u].ka=function(a){var b=this.b[a];b.mb()};U[u].cb=function(a){var b=this.b[a];b.ob()};U[u].t=function(a){var b=this.b[a];b.nb();Q&&S().g[t]==1&&Q.tick("ga_render","ga_srt")};U[u].fa=function(){var a=0;for(var b in this.b)R(this.b[b])||a++;return a};
ca(U[u],function(){var a="[AdData:",b=[];for(var c in this.b)R(this.b[c])||b[q](this.b[c][r]());for(var d in this.B)R(this.B[d])||b[q]("["+d+","+this.B[d]+"]");a+=b[J]();a+="]";return a});U[u].s=function(a){return this.b[a]};U[u].va=function(a,b){if(!(a==g||a[t]==0)){if(b==g||b[t]==0)b="";var c=this.B[a];this.B[a]=c==g?b:c+","+b}};function ob(a,b){S().va(a,b)}M("GA_googleAddAttr",ob);U[u].sa=function(a,b){this.W.N(a,b)};function pb(a,b){S().sa(a,b)}M("GA_googleAddAdSensePageAttr",pb);
U[u].ta=function(a,b,c){if(!(a==g||a[t]==0)){if(T()==g||T().j!="iframe"){var d=this.s(a);if(d==g)return}var f=this.L[a];if(f==g)this.L[a]=new W(this.O);this.L[a].N(b,c)}};function qb(a,b,c){S().ta(a,b,c)}M("GA_googleAddAdSenseSlotAttr",qb);U[u].Pa=function(a){return this.L[a]};var rb=function(a){var b="http://";b+=a?sa:ta;return b+"/gampad/slotdata.js?callback=GA_googleSetAdSlotAttributes"};
U[u].Ha=function(){if(this.r!=g)T().l();else{var a=[];for(var b in this.b)R(this.b[b])||a[q](b);var c=l.GS_googleGetIdsForAdSenseService(),d=l.google_new_gam_domain_enabled==1,f=rb(d)+"&client="+escape(c)+"&page_slots="+escape(a[J]());n[E]("<script src = '"+f+"'><\/script>")}};U[u].setAdSlotAttributes=function(a){this.r=a;T().Z=e;T().l()};function sb(a){S().setAdSlotAttributes(a)}M("GA_googleSetAdSlotAttributes",sb);U[u].ua=function(a,b){if(this.r==g)this.r={};this.r[a]=b;T().Z=e};
U[u].u=function(a){return this.r!=g?this.r[a]:g};function tb(a,b){this.Gb=a;this.ub=b}function ub(a,b){this.AdSlotContent=tb;this.AdSlotConent(ub.HTML_TYPE,a);this._html_=b}ca(ub[u],function(){return"[GA_HTMLAdSlotContent expandable="+this.ub+", html="+this._html_+"]"});ub.prototype=new tb(ub.HTML_TYPE,h);function vb(a,b,c){if(!c||c<0||c>1)c=0;this.Cb=o[ia]()<c;this.xb=a;this.qa=b+"/pagead/gen_204?id="+K(a);this.yb=[]}vb[u].k=function(a,b){if(a&&a.match(/^\w+$/)&&b)this.qa+="&"+a+"="+K(b)};
vb[u].ba=function(){var a=S();for(var b in a.b){var c=a.b[b];if(!R(c)&&c.X!=g){this.k("pub_id",c.X);break}}this.k("nslots",a.fa()[r]());this.k("pub_url",n.URL);this.k("pub_ref",n[ja])};vb[u].ja=function(){if(!this.Cb||!this.xb||!this.qa)return h;var a=new Image;a.src=this.qa;this.yb[q](a);return e};function X(a){this.h=g;this.r={};this.v=this.d="";this.n=a;this.o=this.V=this.D=h;this.j="sync";this.Db=ua;this.K=e;this.Z=h}
X[u].initialize=function(){this.D=l.GA_googleEnv[G]("google_nofetch")!=g||l.google_noFetch;this.V=l.GA_googleEnv[G]("google_norender")!=g;if(this.o=l.GA_googleEnv[G]("google_capture")!=g||l.GA_googleEnv[G]("google_capture_norender")!=g)this.V=e;this.kb(l);this.d=this.v;var a=La(this.fb,this);this.jb(l,a)};X[u].jb=function(a,b){if(a.attachEvent){a.attachEvent("onload",b);return e}if(a.addEventListener){a.addEventListener("load",b,h);return e}return h};
X[u].R=function(a){if(a.google_new_gam_domain_enabled==1)return"http://"+sa;return"http://"+ta};X[u].Q=function(){this.o&&l.GA_googleAdCapture.za(this.h)};X[u].bb=function(){if(this.j=="sync_sra"){var a=S(),b=a.fa(),c=a.g[t];if(b!=c){this.U=new vb("sra_mismatch",this.R(l),na("0.001",0.0010));this.U.k("correlator",this.p);this.U.k("fslots",c[r]());this.U.ba();this.U.ja()}}};X[u].db=function(){if(Q){Q.tick("ga_onload");l.GA_jstiming.report(Q,{e:this.j})}};
X[u].ab=function(){var a=S().Qa();if(a[t]>0){this.J=new vb("missing_cb",this.R(l),na("0.01",0.0010));this.J.k("pending",a[J]());this.J.k("correlator",this.p);this.J.k("impl",this.j);this.J.ba();this.J.ja()}};X[u].fb=function(){this.db();this.Q();this.bb();this.ab()};X[u].kb=function(a){var b=l.GA_googleEnv[G]("google_ad_url");if(b==g||b[t]==0)this.v=this.R(a)+"/gampad/ads?";else{if(b[ga](b[t]-1)!="?")b+="?";this.v=b}};X[u].m=function(){};X[u].Xa=function(){return S().ha(this.K)};
X[u].ga=function(){return S().Ua(this.K)};X[u].z=function(a){return this.h!=g?this.h[a]:g};var xb=function(){var a=i[A],b=a[C]("MSIE ");return b==-1?0:parseFloat(a[H](b+5,a[C](";",b)))},hb=/\+/g;X[u].Ya=function(a){a=a[ma]();if(a[H](0,3)!="ca-")a="ca-"+a;return a};X[u].c=function(a,b){b!=g&&this.a(a,K(b[r]()))};X[u].a=function(a,b){if(b!=g)this.d+=this.d[ga](this.d[t]-1)!="?"?"&"+a+"="+b:a+"="+b};
X[u].Oa=function(a){for(var b=this.Xa(),c=[],d=[],f=[],j=b[t],m=0;m<j;m++){var p=b[m];f[q](p.C);if(!(a!=g&&a!=p.C)){c[q](p.C);d[q](this.Ya(p.X))}}this.c("client",d[0]);if(this.n)f[t]>0&&this.c("page_slots",f[J]());else{this.c("slotname",c[J]());S().g[t]>0&&this.c("page_slots",S().g[J]())}};X[u].Wa=function(a,b){if(b!=g){var c=a.lastIndexOf("?"),d=a[C]("google_preview=",c),f=a[C]("&",d);if(f==-1){f=a[t]-1;d-=1}return a[H](0,d)+a[H](f+1,a[t])}return a};
X[u].Sa=function(a,b){if(Ia(a,b))return b.URL;return b[ja]};X[u].Ra=function(a,b){if(!Ia(a,b))return b[ha];return""};X[u].Va=function(){var a=S().W.getAttribute("google_page_url");if(a)return a;return this.Sa(l,n)};
X[u].Ka=function(a,b,c){this.c("url",this.Wa(this.Va(),l.GA_googleEnv[G]("google_preview")));this.c("ref",n[ja]);this.c("lmt",(Date.parse(n.lastModified)/1000)[r]());this.a("dt",a[I]());if(n.body){var d=n.body.scrollHeight,f=n.body.clientHeight;f&&d&&this.c("cc",o[ea](f*100/d)[r]())}var j=l.GA_googleEnv[G]("deb");j!=g&&this.c("deb",j);var m=l.GA_googleEnv[G]("haonly");m!=g&&this.c("haonly",m);if(i[A][C]("MSIE ")>0){var p=S().W;p.N("google_encoding",n.charset,h)}var z=S().b,D=S().L,N=S().Pa(b);p=S().W;
var V="";if(c)V=mb(z,p,D,this.Db);else{if(N==g)N=p;else N.eb(p);V=N.i()}if(V)this.d+="&"+V};X[u].Na=function(a,b){var c=S().B,d=[];for(var f in c)R(c[f])||d[q](K(f)+"="+K(c[f]));this.c("cust_params",d[J]("&"));if(a._GA_googleCookieHelper){this.c("cookie",a._GA_googleCookieHelper.F);a._GA_googleCookieHelper.ca&&this.c("cookie_enabled","1")}a.google_new_gam_domain_checked==1&&a.google_new_gam_domain_enabled!=1&&this.a("dblk",1);var j=this.Ra(a,b);j&&this.c("cdm",j)};
X[u].La=function(){Oa();var a=l;this.a("ga_vid",a.gaGlobal.vid);this.a("ga_sid",a.gaGlobal.sid);this.a("ga_hid",a.gaGlobal.hid);this.a("ga_fc",a.gaGlobal.from_cookie);this.c("ga_wpids",a.google_analytics_uacct)};
X[u].Za=function(a,b){var c=a[B],d=i.javaEnabled(),f=-b.getTimezoneOffset();if(c){this.a("u_h",c.height);this.a("u_w",c.width);this.a("u_ah",c.availHeight);this.a("u_aw",c.availWidth);this.a("u_cd",c.colorDepth)}this.a("u_tz",f);this.a("u_his",l.history[t]);this.a("u_java",d[r]());i[da]&&this.a("u_nplug",i[da][t]);i.mimeTypes&&this.a("u_nmime",i.mimeTypes[t]);this.a("flash",Aa())};
X[u].i=function(a){this.m();var b=new Date;this.Oa(a);this.Na(l,n);l.GA_googleEnv[G]("google_preview")!=g&&this.a("gct",l.GA_googleEnv[G]("google_preview"));this.La();this.Ka(b,a,this.n);this.Za(l,b);this.d=this.d[H](0,2000);return this.d=this.d[w](/%\w?$/,"")};var yb="google_ads_iframe_"[t];X[u].T=function(a){return"google_ads_iframe_"+a};X[u].A=function(a){var b=a.getAttribute("id"),c=b.substr(yb,b[t]-yb);return c};
X[u].H=function(a,b,c,d,f,j){var m=this.T(a),p=[];if(j){var z=this.S(a);p[q]("<div id=",z,">")}p[q]("<iframe id=",m," name=",m,' width="',d,'" height="',f,'" vspace="0" hspace="0" allowtransparency="true" ',"scrolling=",this.o?'"auto"':'"no"',' marginwidth="0" marginheight="0" frameborder="0" style="border:0px;"',' src="',jb(b),'"');c!=g&&p[q](' onload="',c,'"');p[q]("></iframe>");j&&p[q]("</div>");var D=p[J]("");n[E](D)};
X[u].createDOMIframe=function(a,b){var c=this.z(b),d=c._width_,f=c._height_,j=c._html_,m=n.createElement("iframe");m.id=this.T(b);m.name=this.T(b);m.width=d;m.height=f;m.vspace=0;m.hspace=0;m.allowTransparency="true";m.scrolling="no";m.marginWidth=0;m.marginHeight=0;m.frameBorder=0;m.style.border=0;var p=n.getElementById(a);p.appendChild(m);if(this.o){m[la][x][E](jb(j));m.scrolling="auto"}else m[la][x][E](j);m[la][x].close();S().t(b)};function zb(a,b){T().createDOMIframe(a,b)}
M("GA_googleCreateDomIframe",zb);var Ab=function(){var a=[],b=n.getElementsByTagName("base");if(b)for(var c=0,d=b[t];c<d;++c){var f=b[c],j=f.getAttribute("target");if(j){a[q]({baseElement:f,originalTagValue:j});f.removeAttribute("target")}}return a},Bb=function(a){if(a)for(var b=0,c=a[t];b<c;++b){var d=a[b];d.baseElement.setAttribute("target",d.originalTagValue)}},Cb=function(a){var b="http://"+ra+"/pagead/inject_object_div.js";if(k(xb(),10)>6)return h;if(a[C](b)<0)return h;return e};
X[u].xa=function(a,b){if(this.o)b=jb(b);var c=Ab();l.frames[a.name].contents=b;a.src=Cb(b)?'javascript:document.write(window["contents"]);document.close();':'javascript:window["contents"]';Bb(c)};
X[u].ya=function(a,b){var c=this.A(a),d=a[la]?a[la][x]:a.contentDocument;if(d==g)if(n.implementation&&n.implementation.createDocument)d=n.implementation.createDocument("",c,g);else if(typeof ActiveXObject!="undefined")d=new ActiveXObject("Msxml.DOMDocument");else return;d.open("text/html","replace");this.o?d[E](jb(b)):d[E](b);d.close()};
X[u].loadiframe=function(a){var b=this.A(a),c=S().s(b);if(!c.ia){c.ia=e;var d=this.z(b),f=a.parentNode;if(d==g||d._html_==g){f.removeChild(a);S().t(b)}else if(d._expandable_){f.innerHTML=d._html_;S().t(b)}else{d._is_3pas_?this.xa(a,d._html_):this.ya(a,d._html_);S().t(b)}}};X[u].S=function(a){return"google_ads_div_"+a};X[u].Ba=function(a){var b=this.S(a),c="<div id="+b+">",d=this.z(a);if(!(d==g)){c+=d._html_;c+="\n</div>\n";n[E](c);S().t(a)}};
X[u].Aa=function(a){var b=this.S(a),c="<div id="+b+">";c+="\n</div>\n";n[E](c);return b};X[u].G=function(){if(!this.K)return e;if(this.ga()>0)return e;else if(S().Ta()==0)return h};X[u].setAdContentsBySlot=function(a){Q&&S().g[t]==1&&Q.tick("ga_srt","_ga_start");if(this.h==g){this.h=a;for(var b in a)R(a[b])||S().ka(b)}else for(b in a)if(!R(a[b])){this.h[b]=a[b];S().ka(b)}var c=h;for(b in a)if(!R(a[b])){var d=a[b];if(c){d._cookies_=[l._GA_googleCookieHelper.Ma()];c=h}d!=g&&d._cookies_!=g&&l._GA_googleCookieHelper.setCookieInfo(d)}};
function Db(a){T().setAdContentsBySlot(a)}M("GA_googleSetAdContentsBySlot",Db);function Y(a){X[F](this,a);this.K=h;this.p=(new Date)[I]();this.j=a?"sync_sra":"sync"}Ma(Y,X);
Y[u].m=function(){this.d=this.v;this.c("correlator",this.p[r]());this.a("output","json_html");this.a("callback","GA_googleSetAdContentsBySlotForSync");this.n?this.a("impl","ss"):this.a("impl","s");var a=0,b=e;for(var c in this.h)if(!R(this.h[c])){var d=this.h[c];if(d._is_afc_==aa){b=h;break}else a=2*a+(d._is_afc_?1:0)}b&&this.a("prev_afc",a);this.n||this.wa(S().g,this.h)};
Y[u].wa=function(a,b){if(a&&b){for(var c=[],d=[],f=a[t]-1,j=0;j<f;j++){var m=a[j],p=b[m];if(p&&p._cids_&&p._a2ids_){c[q](p._cids_[0]);d[q](p._a2ids_[0])}else{c[q]("");d[q]("")}}if(c[t]>0){var z=c[J](","),D=d[J](",");this.c("a2ids",D);this.c("cids",z)}}};Y[u].Ea=function(a){var b=S().b,c=b[a];if(!(c==g))if(!this.D){this.i(c.C);S().la(a);n[E]("<script src = '"+this.d+"'><\/script>")}};
Y[u].setAdContentsBySlotForSync=function(a){this.setAdContentsBySlot(a);if(this.n)if(S().g[t]==1){var b=S().g[0];this.Y(b);return}for(var c in a)R(a[c])||this.Y(c)};function Eb(a){T().setAdContentsBySlotForSync(a)}M("GA_googleSetAdContentsBySlotForSync",Eb);Y[u].l=function(){this.G()};Y[u].Da=function(){this.i(g);n[E]("<script src = '"+this.d+"'><\/script>");S().ma()};Y[u].q=function(a){S().g[q](a);Q&&S().g[t]==1&&Q.tick("_ga_start");if(this.n)S().g[t]==1?this.Da():this.Y(a);else this.Ea(a)};
Y[u].Ia=function(a,b){if(a.google_js_backfill){var c="script";b[E]("<"+c+' src="http://pagead2.googlesyndication.com/pagead/show_ads.js"></'+c+">")}};Y[u].Y=function(a){this.Ja(l,n,a)};
Y[u].Ja=function(a,b,c){var d=S().s(c);if(!(d==g)){var f=this.z(c);S().cb(c);if(f==g||f._empty_){this.Ia(a,b,c);S().t(c)}else if(this.V&&!this.o)S().t(c);else if(f._snippet_&&!f._is_afc_&&!this.o)this.Ba(c);else if(i[A][C]("MSIE ")>0){var j="GA_googleSyncAdSlotLoaded(this);";this.H(c,"about:blank",j,f._width_,f._height_,e)}else{var m=this.Aa(c);b[E]("<script>GA_googleCreateDomIframe('"+m+"' ,'"+c+"');<\/script>")}}};Y[u].syncAdSlotLoaded=function(a){var b=this.A(a);S().s(b);this.loadiframe(a)};
function Fb(a){T().syncAdSlotLoaded(a)}M("GA_googleSyncAdSlotLoaded",Fb);function Z(a){X[F](this,a);this.p=(new Date)[I]();this.j="async"}Ma(Z,X);Z[u].m=function(){this.d=this.v;this.lb();this.c("correlator",this.p[r]());this.a("output","json_html");this.a("callback","GA_googleSetAdContentsBySlot");this.a("impl","a")};Z[u].lb=function(){this.delay=500;var a=l.GA_googleEnv[G]("google_async_delay");if(a!=g)this.delay=1000*a};
Z[u].l=function(){if(this.G())this.D||l.setTimeout("GA_googleReallyFetchAds();",this.INITIAL_ASYNC_DELAY)};Z[u].reallyFetchAds=function(){if(!(this.ga()==0)){var a=n.getElementsByTagName("head")[0];if(this.n){var b=n.createElement("script");b.src=this.i(g);a.appendChild(b);S().ma()}else{var c=S().b;for(var d in c)if(!R(c[d])){b=n.createElement("script");b.src=this.i(d);a.appendChild(b);S().la(d)}}}};function Gb(){T().reallyFetchAds()}M("GA_googleReallyFetchAds",Gb);
Z[u].q=function(a){var b=S().s(a);if(!(b==g)){S().g[q](a);var c="GA_googleAsyncAdSlotLoaded(this);",d=S().u(a);this.H(a,"about:blank",c,d._width_,d._height_,e)}};Z[u].asyncAdSlotLoaded=function(a){var b=this.A(a);S().s(b);!this.D&&!this.V&&this.ra(a)};function Hb(a){T().asyncAdSlotLoaded(a)}M("GA_googleAsyncAdSlotLoaded",Hb);Z[u].ra=function(a){var b=this.A(a),c=S().s(b);if(this.h==g||this.h[b]==g){if(!(c.pa>30)){l.setTimeout(function(){T().ra(a)},this.delay);c.pa++}}else this.loadiframe(a)};
Z[u].Q=function(){};function $(a){X[F](this,a);this.p=(new Date)[I]();this.j="fallback"}Ma($,X);$[u].m=function(){this.d=this.v;this.c("correlator",this.p[r]());this.a("output","html");this.a("impl","fb")};$[u].l=function(){this.G()};$[u].I=function(a){var b;if(this.n){this.i(g);b=this.d+"&currentslot="+K(a)}else b=this.i(a);return b};$[u].q=function(a){var b=S().u(a);if(!(b==g)){S().g[q](a);if(!this.D){var c=this.I(a);this.H(a,c,g,b._width_,b._height_,e)}}};
function Ib(a){X[F](this,a);this.p=(new Date)[I]();this.Z=e;this.j="iframe"}Ma(Ib,X);Ib[u].m=function(){this.d=this.v;this.c("correlator",this.p[r]());this.a("output","html");this.a("impl","ifr")};Ib[u].l=function(){this.G()};Ib[u].I=function(a){var b;if(this.n){this.i(g);b=this.d+"&currentslot="+K(a)}else b=this.i(a);return b};Ib[u].q=function(a){var b=S().u(a);if(!(b==g)){S().g[q](a);if(!this.D){var c=this.I(a);this.H(a,c,g,b._width_,b._height_,e)}}};
var Jb=function(){if(za()){var a=xb();return a<=5}else if(xa("firefox")){var b=i[A][C]("Firefox")+8,c=k(i[A][ga](b),10),d=i[A][v](b);return c<1}else if(xa("safari")){b=i[A][C]("Safari")+7;d=i[A][v](b);var f=k(d,10);return f<412}else if(l.opera!=g){b=i[A][C]("Opera")+6;d=i[A][v](b);c=k(d,10);return c<9}else if(!za()&&!xa("safari")&&xa("mozilla")){b=i[A][C]("Netscape")+9;d=i[A][v](b);c=k(d,10);return c<7}else return e},Kb=function(){if(za()){var a=xb();return a>5}else if(xa("firefox")){var b=i[A][C]("Firefox")+
8,c=k(i[A][ga](b),10);i[A][v](b);return c>1}return h},Lb=function(){if(Jb())return"fallback";else if(l.google_delayFetch&&Kb())return"async";return"sync"},Wa=function(a){var b=g;if(typeof a!="undefined"&&a!=g)b=a;else{b=l.GA_googleEnv[G]("google_ad_impl");if(b==g)b=Lb()}switch(b){case "async":return new Z(h);case "sync":return new Y(h);case "sync_sra":return new Y(e);case "fallback":return new $(h);case "iframe":return new Ib(h);default:return new $(h)}};if(Q){Q.tick("js_parse","js_load");Q.tick("jl")}var Mb;
function S(){Mb||(Mb=new U(ua));return Mb}function db(a){delete Mb;Mb=a}var Nb;function T(){Nb||(Nb=g);return Nb}function Va(a){delete Nb;Nb=a}if(typeof l.GA_googleEnv=="undefined")l.GA_googleEnv=new ib;if(typeof l.GA_googleAdCapture=="undefined")l.GA_googleAdCapture=new kb;if(l._GA_googleCookieHelper==g)l._GA_googleCookieHelper=new L;
})()
