(function(){
var h=true,l=null,m=false,n=(new Date).getTime();document.URL&&(document.URL.indexOf("?google_debug")>0||document.URL.indexOf("&google_debug")>0);function o(a,b){var c=parseFloat(a);return isNaN(c)||c>1||c<0?b:c}function p(a,b){var c=/^([\w-]+\.)+[\w-]{2,}(\:[0-9]+)?$/;return c.test(a)?a:b};var aa="pagead2.googlesyndication.com",ba="googleads.g.doubleclick.net",ca="pubads.g.doubleclick.net",da="partner.googleadservices.com",q=p("pagead2.googlesyndication.com",aa),ea=p("googleads.g.doubleclick.net",ba),fa=p("pagead2.googlesyndication.com",aa);p("pubads.g.doubleclick.net",ca);var ga=p("partner.googleadservices.com",da);var ha={google_ad_channel:"channel",google_ad_host:"host",google_ad_host_channel:"h_ch",google_ad_host_tier_id:"ht_id",google_ad_region:"region",google_ad_section:"region",google_ad_type:"ad_type",google_adtest:"adtest",google_allow_expandable_ads:"ea",google_alternate_ad_url:"alternate_ad_url",google_alternate_color:"alt_color",google_bid:"bid",google_city:"gcs",google_color_bg:"color_bg",google_color_border:"color_border",google_color_line:"color_line",google_color_link:"color_link",google_color_text:"color_text",
google_color_url:"color_url",google_contents:"contents",google_country:"gl",google_cust_age:"cust_age",google_cust_ch:"cust_ch",google_cust_gender:"cust_gender",google_cust_id:"cust_id",google_cust_interests:"cust_interests",google_cust_job:"cust_job",google_cust_l:"cust_l",google_cust_lh:"cust_lh",google_cust_u_url:"cust_u_url",google_disable_video_autoplay:"disable_video_autoplay",google_ed:"ed",google_encoding:"oe",google_feedback:"feedback_link",google_flash_version:"flash",google_font_face:"f",
google_gl:"gl",google_hints:"hints",google_kw:"kw",google_kw_type:"kw_type",google_language:"hl",google_page_url:"url",google_referrer_url:"ref",google_region:"gr",google_reuse_colors:"reuse_colors",google_safe:"adsafe",google_tag_info:"gut",google_targeting:"targeting",google_ui_features:"ui",google_ui_version:"uiv",google_video_doc_id:"video_doc_id",google_video_product_type:"video_product_type"},ia={google_ad_format:"format",google_ad_output:"output",google_ad_callback:"callback",google_ad_height:"h",
google_ad_override:"google_ad_override",google_ad_slot:"slotname",google_ad_width:"w",google_analytics_uacct:"ga_wpids",google_correlator:"correlator",google_cpa_choice:"cpa_choice",google_ctr_threshold:"ctr_t",google_image_size:"image_size",google_last_modified_time:"lmt",google_max_num_ads:"num_ads",google_max_radlink_len:"max_radlink_len",google_num_radlinks:"num_radlinks",google_num_radlinks_per_unit:"num_radlinks_per_unit",google_only_ads_with_video:"only_ads_with_video",google_page_location:"loc",
google_rl_dest_url:"rl_dest_url",google_rl_filtering:"rl_filtering",google_rl_mode:"rl_mode",google_rt:"rt",google_skip:"skip"},ja={google_only_pyv_ads:"pyv"};function ka(a){return ha[a]||ia[a]||ja[a]||l};function la(a){return typeof encodeURIComponent=="function"?encodeURIComponent(a):escape(a)}function ma(a,b,c){var d=document.createElement("script");d.type="text/javascript";if(b)d.onload=b;if(c)d.id=c;d.src=a;var e=document.getElementsByTagName("head")[0];if(!e)return m;window.setTimeout(function(){e.appendChild(d)},0);return h}function na(a){if(a in oa)return oa[a];return oa[a]=navigator.userAgent.toLowerCase().indexOf(a)!=-1}var oa={};
function pa(){if(navigator.plugins&&navigator.mimeTypes.length){var a=navigator.plugins["Shockwave Flash"];if(a&&a.description)return a.description.replace(/([a-zA-Z]|\s)+/,"").replace(/(\s)+r/,".")}else if(navigator.userAgent&&navigator.userAgent.indexOf("Windows CE")>=0){for(var b=3,c=1;c;)try{c=new ActiveXObject("ShockwaveFlash.ShockwaveFlash."+(b+1));b++}catch(d){c=l}return b.toString()}else if(na("msie")&&!window.opera){c=l;try{c=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.7")}catch(e){b=
0;try{c=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.6");b=6;c.AllowScriptAccess="always"}catch(f){if(b==6)return b.toString()}try{c=new ActiveXObject("ShockwaveFlash.ShockwaveFlash")}catch(j){}}if(c){b=c.GetVariable("$version").split(" ")[1];return b.replace(/,/g,".")}}return"0"}function qa(a){var b=a.google_ad_format;if(b)return b.indexOf("_0ads")>0;return a.google_ad_output!="html"&&a.google_num_radlinks>0}function r(a){return!!a&&a.indexOf("_sdo")!=-1}
function ra(a){return qa(a)||r(a.google_ad_format)}function s(a,b){var c=Math.random();if(c<b){var d=Math.floor(c/b*a.length);return a[d]}return""};function w(){this.b=this.C();this.o=m;if(!this.b)this.o=this.p()}w.prototype.h="__gads=";w.prototype.e="GoogleAdServingTest=";w.prototype.v=function(){return this.b};w.prototype.setCookieInfo=function(a){this.a=a._cookies_[0];if(this.a!=l){this.b=this.a._value_;this.I()}};w.prototype.t=function(a){var b=(new Date).valueOf(),c=new Date;c.setTime(b+a);return c};var sa="http://"+ga+"/gampad/cookie.js?callback=_GA_googleCookieHelper.setCookieInfo";
w.prototype.q=function(a){if(!(this.b||!this.o)){var b="script",c=document.domain,d=sa+"&client="+la(a)+"&domain="+la(c);document.write("<"+b+' src="'+d+'"></'+b+">")}};w.prototype.p=function(){document.cookie=this.e+"Good";var a=this.n(this.e),b=a=="Good";if(b){var c=this.t(-1);document.cookie=this.e+"; expires="+c.toGMTString()}return b};w.prototype.C=function(){var a=this.n(this.h);return a};
w.prototype.n=function(a){var b=document.cookie,c=b.indexOf(a),d="";if(c!=-1){var e=c+a.length,f=b.indexOf(";",e);if(f==-1)f=b.length;d=b.substring(e,f)}return d};w.prototype.I=function(){if(!(this.a==l))if(this.b){var a=new Date;a.setTime(1000*this.a._expires_);var b=this.a._domain_,c=this.h+this.b+"; expires="+a.toGMTString()+"; path="+this.a._path_+"; domain=."+b;document.cookie=c}};var x=this,ta=function(a,b,c){var d=a.split("."),e=c||x;!(d[0]in e)&&e.execScript&&e.execScript("var "+d[0]);for(var f;d.length&&(f=d.shift());)if(!d.length&&b!==undefined)e[f]=b;else e=e[f]?e[f]:(e[f]={})},A=function(a){var b=typeof a;if(b=="object")if(a){if(a instanceof Array||!(a instanceof Object)&&Object.prototype.toString.call(a)=="[object Array]"||typeof a.length=="number"&&typeof a.splice!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("splice"))return"array";
if(!(a instanceof Object)&&(Object.prototype.toString.call(a)=="[object Function]"||typeof a.call!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("call")))return"function"}else return"null";else if(b=="function"&&typeof a.call=="undefined")return"object";return b},xa=function(a){var b=A(a);return b=="array"||b=="object"&&typeof a.length=="number"},B=function(a){return typeof a=="string"},ya=function(a){var b=A(a);return b=="object"||b=="array"||b=="function"};
Math.floor(Math.random()*2147483648).toString(36);var za=function(a){var b=A(a);if(b=="object"||b=="array"){if(a.clone)return a.clone.call(a);var c=b=="array"?[]:{};for(var d in a)c[d]=za(a[d]);return c}return a},Aa=Date.now||function(){return(new Date).getTime()},C=function(a,b,c){ta(a,b,c)};var Ba=function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")},Ha=function(a,b){if(b)return a.replace(Ca,"&amp;").replace(Da,"&lt;").replace(Ea,"&gt;").replace(Fa,"&quot;");else{if(!Ga.test(a))return a;if(a.indexOf("&")!=-1)a=a.replace(Ca,"&amp;");if(a.indexOf("<")!=-1)a=a.replace(Da,"&lt;");if(a.indexOf(">")!=-1)a=a.replace(Ea,"&gt;");if(a.indexOf('"')!=-1)a=a.replace(Fa,"&quot;");return a}},Ca=/&/g,Da=/</g,Ea=/>/g,Fa=/\"/g,Ga=/[&<>\"]/,Ka=function(a){if(D(a,"&"))return"document"in x&&!D(a,"<")?
Ia(a):Ja(a);return a},Ia=function(a){var b=x.document.createElement("a");b.innerHTML=a;b.normalize&&b.normalize();a=b.firstChild.nodeValue;b.innerHTML="";return a},Ja=function(a){return a.replace(/&([^;]+);/g,function(b,c){switch(c){case "amp":return"&";case "lt":return"<";case "gt":return">";case "quot":return'"';default:if(c.charAt(0)=="#"){var d=Number("0"+c.substr(1));if(!isNaN(d))return String.fromCharCode(d)}return b}})},La=function(a,b){for(var c=b.length,d=0;d<c;d++){var e=c==1?b:b.charAt(d);
if(a.charAt(0)==e&&a.charAt(a.length-1)==e)return a.substring(1,a.length-1)}return a},D=function(a,b){return a.indexOf(b)!=-1},Na=function(a,b){for(var c=0,d=Ba(String(a)).split("."),e=Ba(String(b)).split("."),f=Math.max(d.length,e.length),j=0;c==0&&j<f;j++){var k=d[j]||"",i=e[j]||"",g=new RegExp("(\\d*)(\\D*)","g"),z=new RegExp("(\\d*)(\\D*)","g");do{var u=g.exec(k)||["","",""],v=z.exec(i)||["","",""];if(u[0].length==0&&v[0].length==0)break;var t=u[1].length==0?0:parseInt(u[1],10),K=v[1].length==
0?0:parseInt(v[1],10);c=Ma(t,K)||Ma(u[2].length==0,v[2].length==0)||Ma(u[2],v[2])}while(c==0)}return c},Ma=function(a,b){if(a<b)return-1;else if(a>b)return 1;return 0};Aa();var E=function(a){this.H=a;this.m=[];this.B=this.l=0;this.g=[];this.z=m};E.prototype.G=function(a,b){var c=this.H[b],d=this.m;this.H[b]=function(e){if(e&&e.length>0){var f=e.length>1?e[1].url:l;d.push([a,Ka(e[0].url),f])}c(e)}};E.prototype.F=function(){this.l++};E.prototype.A=function(){if(!this.z){ma("http://"+q+"/pagead/osd.js");this.z=h}};E.prototype.r=function(a){if(this.l>0)for(var b=document.getElementsByTagName("iframe"),c=0;c<b.length;c++)b.item(c).name=="google_ads_frame"&&a(b.item(c),b.item(c).src)};
E.prototype.s=function(a){var b=this.m;if(b.length>0)for(var c=document.getElementsByTagName("a"),d=function(g,z){return g.innerHTML.indexOf(z)>0},e=0;e<c.length;e++)for(var f=0;f<b.length;f++)if(c.item(e).href==b[f][1]){var j=c.item(e).parentNode;if(b[f][2])for(var k=j,i=0;i<4;i++){if(d(k,b[f][2])){j=k;break}k=k.parentNode}a(j,b[f][0]);b.splice(f,1);break}};E.prototype.i=function(a){this.s(a);this.r(a)};E.prototype.c=function(a){this.B=a};E.prototype.k=function(){return this.B};
E.prototype.j=function(){return this.m.length+this.l};E.prototype.d=function(a){this.g=a};E.prototype.D=function(a,b){if(this.g.length>0){for(var c=0;c<this.g.length;c++)if(this.g[c]==a)if(a=="js")this.G(b,"google_ad_request_done");else a=="html"&&this.F();this.A()}};var Oa=function(){window.__google_ad_urls||(window.__google_ad_urls=new E(window));return window.__google_ad_urls};C("Goog_AdSense_getAdAdapterInstance",Oa);C("Goog_AdSense_OsdAdapter",E);
C("Goog_AdSense_OsdAdapter.prototype.numBlocks",E.prototype.j);C("Goog_AdSense_OsdAdapter.prototype.findBlocks",E.prototype.i);C("Goog_AdSense_OsdAdapter.prototype.getOsdMode",E.prototype.k);function Pa(a,b){try{return a.top.document.URL==b.URL}catch(c){}return m}function Qa(a,b,c,d){var e=c||a.google_ad_width,f=d||a.google_ad_height;if(Pa(a,b))return m;var j=b.documentElement;if(e&&f){var k=1,i=1;if(a.innerHeight){k=a.innerWidth;i=a.innerHeight}else if(j&&j.clientHeight){k=j.clientWidth;i=j.clientHeight}else if(b.body){k=b.body.clientWidth;i=b.body.clientHeight}if(i>2*f||k>2*e)return m}return h}function Ra(a,b){for(var c in b)a["google_"+c]=b[c]}
function Sa(a,b){if(!b)return a.URL;return a.referrer}function Ta(a,b){if(!b&&a.google_referrer_url==l)return"0";else if(b&&a.google_referrer_url==l)return"1";else if(!b&&a.google_referrer_url!=l)return"2";else if(b&&a.google_referrer_url!=l)return"3";return"4"}function Ua(a,b,c,d){a.page_url=Sa(c,d);a.page_location=l}function Va(a,b,c,d){a.page_url=b.google_page_url;a.page_location=Sa(c,d)||"EMPTY"}
function Wa(a,b){var c={},d=Qa(a,b,a.google_ad_width,a.google_ad_height);c.iframing=Ta(a,d);a.google_page_url?Va(c,a,b,d):Ua(c,a,b,d);c.last_modified_time=b.URL==c.page_url?Date.parse(b.lastModified)/1000:l;c.referrer_url=d?a.google_referrer_url:a.google_page_url&&a.google_referrer_url?a.google_referrer_url:b.referrer;return c}function Xa(a){var b={},c=a.URL.substring(a.URL.lastIndexOf("http"));b.iframing=l;b.page_url=c;b.page_location=a.URL;b.last_modified_time=l;b.referrer_url=c;return b}
function Ya(a,b){var c=Za(a,b);Ra(a,c)}function Za(a,b){var c;return c=a.google_page_url==l&&$a[b.domain]?Xa(b):Wa(a,b)}var $a={};$a["ad.yieldmanager.com"]=h;var ab=function(a,b,c){if(a.forEach)a.forEach(b,c);else if(Array.forEach)Array.forEach(a,b,c);else for(var d=a.length,e=B(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)},bb=function(a){if(A(a)=="array")return a.concat();else{for(var b=[],c=0,d=a.length;c<d;c++)b[c]=a[c];return b}};var F=function(a,b){this.x=a!==undefined?a:0;this.y=b!==undefined?b:0};F.prototype.clone=function(){return new F(this.x,this.y)};F.prototype.toString=function(){return"("+this.x+", "+this.y+")"};var G=function(a,b){this.width=a;this.height=b};G.prototype.clone=function(){return new G(this.width,this.height)};G.prototype.toString=function(){return"("+this.width+" x "+this.height+")"};G.prototype.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};G.prototype.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};
G.prototype.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};G.prototype.scale=function(a){this.width*=a;this.height*=a;return this};var cb=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)};var H,db,I,eb,fb,gb,hb,ib,jb,kb,mb=function(){return x.navigator?x.navigator.userAgent:l},J=function(){return x.navigator},qb=function(){gb=fb=eb=I=db=H=m;var a;if(a=mb()){var b=J();H=a.indexOf("Opera")==0;db=!H&&a.indexOf("MSIE")!=-1;eb=(I=!H&&a.indexOf("WebKit")!=-1)&&a.indexOf("Mobile")!=-1;gb=(fb=!H&&!I&&b.product=="Gecko")&&b.vendor=="Camino"}};qb();
var L=H,M=db,rb=fb,N=I,sb=eb,tb=function(){var a=J();return a&&a.platform||""},ub=tb(),vb=function(){hb=D(ub,"Mac");ib=D(ub,"Win");jb=D(ub,"Linux");kb=!!J()&&D(J().appVersion||"","X11")};vb();
var wb=hb,xb=ib,yb=jb,zb=function(){var a="",b;if(L&&x.opera){var c=x.opera.version;a=typeof c=="function"?c():c}else{if(rb)b=/rv\:([^\);]+)(\)|;)/;else if(M)b=/MSIE\s+([^\);]+)(\)|;)/;else if(N)b=/WebKit\/(\S+)/;if(b){var d=b.exec(mb());a=d?d[1]:""}}return a},Ab=zb(),Bb={},O=function(a){return Bb[a]||(Bb[a]=Na(Ab,a)>=0)};var Cb;var Db=function(a){return B(a)?document.getElementById(a):a},Eb=Db,Gb=function(a,b){cb(b,function(c,d){if(d=="style")a.style.cssText=c;else if(d=="class")a.className=c;else if(d=="for")a.htmlFor=c;else if(d in Fb)a.setAttribute(Fb[d],c);else a[d]=c})},Fb={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",rowspan:"rowSpan",valign:"vAlign",height:"height",width:"width",usemap:"useMap",frameborder:"frameBorder",type:"type"},Hb=function(a){var b=a.document;if(N&&!O("500")&&!sb){if(typeof a.innerHeight==
"undefined")a=window;var c=a.innerHeight,d=a.document.documentElement.scrollHeight;if(a==a.top)if(d<c)c-=15;return new G(a.innerWidth,c)}var e=b.compatMode=="CSS1Compat"&&(!L||L&&O("9.50"))?b.documentElement:b.body;return new G(e.clientWidth,e.clientHeight)},Ib=function(a){var b=!N&&a.compatMode=="CSS1Compat"?a.documentElement:a.body;return new F(b.scrollLeft,b.scrollTop)},Kb=function(){return Jb(document,arguments)},Jb=function(a,b){var c=b[0],d=b[1];if(M&&d&&(d.name||d.type)){var e=["<",c];d.name&&
e.push(' name="',Ha(d.name),'"');if(d.type){e.push(' type="',Ha(d.type),'"');d=za(d);delete d.type}e.push(">");c=e.join("")}var f=a.createElement(c);if(d)if(B(d))f.className=d;else Gb(f,d);if(b.length>2){function j(g){if(g)f.appendChild(B(g)?a.createTextNode(g):g)}for(var k=2;k<b.length;k++){var i=b[k];xa(i)&&!(ya(i)&&i.nodeType>0)?ab(Lb(i)?bb(i):i,j):j(i)}}return f},Mb=function(a,b){a.appendChild(b)},Nb=function(a){return a&&a.parentNode?a.parentNode.removeChild(a):l},Ob=function(a,b){var c=b.parentNode;
c&&c.replaceChild(a,b)},Pb=N&&Na(Ab,"521")<=0,Qb=function(a,b){if(typeof a.contains!="undefined"&&!Pb&&b.nodeType==1)return a==b||a.contains(b);if(typeof a.compareDocumentPosition!="undefined")return a==b||Boolean(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a},P=function(a){return a.nodeType==9?a:a.ownerDocument||a.document},Lb=function(a){if(a&&typeof a.length=="number")if(ya(a))return typeof a.item=="function"||typeof a.item=="string";else if(A(a)=="function")return typeof a.item==
"function";return m},Q=function(a){this.f=a||x.document||document};Q.prototype.createElement=function(a){return this.f.createElement(a)};Q.prototype.createTextNode=function(a){return this.f.createTextNode(a)};Q.prototype.w=function(){return this.f.compatMode=="CSS1Compat"};Q.prototype.u=function(){return Ib(this.f)};Q.prototype.appendChild=Mb;Q.prototype.removeNode=Nb;Q.prototype.replaceNode=Ob;Q.prototype.contains=Qb;var Rb,Sb,Tb,Ub,Vb,Wb,Xb=function(){Wb=Vb=Ub=Tb=Sb=Rb=m;var a=mb();if(a)if(a.indexOf("Firefox")!=-1)Rb=h;else if(a.indexOf("Camino")!=-1)Sb=h;else if(a.indexOf("iPhone")!=-1||a.indexOf("iPod")!=-1)Tb=h;else if(a.indexOf("Android")!=-1)Ub=h;else if(a.indexOf("Chrome")!=-1)Vb=h;else if(a.indexOf("Safari")!=-1)Wb=h};Xb();var Yb=function(a,b){var c=P(a);if(c.defaultView&&c.defaultView.getComputedStyle){var d=c.defaultView.getComputedStyle(a,"");if(d)return d[b]}return l},R=function(a,b){return Yb(a,b)||(a.currentStyle?a.currentStyle[b]:l)||a.style[b]},Zb=function(a){var b;b=a?a.nodeType==9?a:P(a):document;if(M&&!(b?new Q(P(b)):Cb||(Cb=new Q)).w())return b.body;return b.documentElement},$b=function(a){var b=a.getBoundingClientRect();if(M){var c=a.ownerDocument;b.left-=c.documentElement.clientLeft+c.body.clientLeft;
b.top-=c.documentElement.clientTop+c.body.clientTop}return b},ac=function(a){if(M)return a.offsetParent;for(var b=P(a),c=R(a,"position"),d=c=="fixed"||c=="absolute",e=a.parentNode;e&&e!=b;e=e.parentNode){c=R(e,"position");d=d&&c=="static"&&e!=b.documentElement&&e!=b.body;if(!d&&(e.scrollWidth>e.clientWidth||e.scrollHeight>e.clientHeight||c=="fixed"||c=="absolute"))return e}return l},bc=function(a){var b,c=P(a),d=R(a,"position"),e=rb&&c.getBoxObjectFor&&!a.getBoundingClientRect&&d=="absolute"&&(b=
c.getBoxObjectFor(a))&&(b.screenX<0||b.screenY<0),f=new F(0,0),j=Zb(c);if(a==j)return f;if(a.getBoundingClientRect){b=$b(a);var k=(c?new Q(P(c)):Cb||(Cb=new Q)).u();f.x=b.left+k.x;f.y=b.top+k.y}else if(c.getBoxObjectFor&&!e){b=c.getBoxObjectFor(a);var i=c.getBoxObjectFor(j);f.x=b.screenX-i.screenX;f.y=b.screenY-i.screenY}else{var g=a;do{f.x+=g.offsetLeft;f.y+=g.offsetTop;if(g!=a){f.x+=g.clientLeft||0;f.y+=g.clientTop||0}if(N&&R(g,"position")=="fixed"){f.x+=c.body.scrollLeft;f.y+=c.body.scrollTop;
break}g=g.offsetParent}while(g&&g!=a);if(L||N&&d=="absolute")f.y-=c.body.offsetTop;for(g=a;(g=ac(g))&&g!=c.body;){f.x-=g.scrollLeft;if(!L||g.tagName!="TR")f.y-=g.scrollTop}}return f};rb&&O("1.9");
var cc=function(a,b,c,d){if(/^\d+px?$/.test(b))return parseInt(b,10);else{var e=a.style[c],f=a.runtimeStyle[c];a.runtimeStyle[c]=a.currentStyle[c];a.style[c]=b;var j=a.style[d];a.style[c]=e;a.runtimeStyle[c]=f;return j}},dc=function(a){var b=P(a),c="";if(b.createTextRange){var d=b.body.createTextRange();d.moveToElementText(a);c=d.queryCommandValue("FontName")}if(!c){c=R(a,"fontFamily");if(L&&yb)c=c.replace(/ \[[^\]]*\]/,"")}var e=c.split(",");if(e.length>1)c=e[0];return La(c,"\"'")},ec=function(a){var b=
a.match(/[^\d]+$/);return b&&b[0]||l},fc={cm:1,"in":1,mm:1,pc:1,pt:1},gc={em:1,ex:1},hc=function(a){var b=R(a,"fontSize"),c=ec(b);if(b&&"px"==c)return parseInt(b,10);if(M)if(c in fc)return cc(a,b,"left","pixelLeft");else if(a.parentNode&&a.parentNode.nodeType==1&&c in gc){var d=a.parentNode,e=R(d,"fontSize");return cc(d,b==e?"1em":b,"left","pixelLeft")}var f=Kb("span",{style:"visibility:hidden;position:absolute;line-height:0;padding:0;margin:0;border:0;height:1em;"});Mb(a,f);b=f.offsetHeight;Nb(f);
return b};var S=document,T=navigator,U=window;
function ic(){var a=S.cookie,b=Math.round((new Date).getTime()/1000),c=U.google_analytics_domain_name,d=typeof c=="undefined"?jc("auto"):jc(c),e=a.indexOf("__utma="+d+".")>-1,f=a.indexOf("__utmb="+d)>-1,j=a.indexOf("__utmc="+d)>-1,k,i={},g=!!U&&!!U.gaGlobal;if(e){k=a.split("__utma="+d+".")[1].split(";")[0].split(".");i.sid=f&&j?k[3]+"":g&&U.gaGlobal.sid?U.gaGlobal.sid:b+"";i.vid=k[0]+"."+k[1];i.from_cookie=h}else{i.sid=g&&U.gaGlobal.sid?U.gaGlobal.sid:b+"";i.vid=g&&U.gaGlobal.vid?U.gaGlobal.vid:(Math.round(Math.random()*
2147483647)^kc()&2147483647)+"."+b;i.from_cookie=m}i.dh=d;i.hid=g&&U.gaGlobal.hid?U.gaGlobal.hid:Math.round(Math.random()*2147483647);return U.gaGlobal=i}
function kc(){var a=S.cookie?S.cookie:"",b=U.history.length,c,d,e=[T.appName,T.version,T.language?T.language:T.browserLanguage,T.platform,T.userAgent,T.javaEnabled()?1:0].join("");if(U.screen)e+=U.screen.width+"x"+U.screen.height+U.screen.colorDepth;else if(U.java){d=java.awt.Toolkit.getDefaultToolkit().getScreenSize();e+=d.screen.width+"x"+d.screen.height}e+=a;e+=S.referrer?S.referrer:"";for(c=e.length;b>0;)e+=b--^c++;return lc(e)}
function lc(a){var b=1,c=0,d,e;if(!(a==undefined||a=="")){b=0;for(d=a.length-1;d>=0;d--){e=a.charCodeAt(d);b=(b<<6&268435455)+e+(e<<14);c=b&266338304;b=c!=0?b^c>>21:b}}return b}function jc(a){if(!a||a==""||a=="none")return 1;if("auto"==a){a=S.domain;if("www."==a.substring(0,4))a=a.substring(4,a.length)}return lc(a.toLowerCase())};var mc="";function nc(a){if(a){if(mc!="")mc+=",";mc+=a}}function oc(a){if(a&&a instanceof Array)for(var b=0;b<a.length;b++)a[b]&&typeof a[b]=="string"&&nc(a[b])}var pc=m;
function qc(a,b){var c="script";(pc=rc(a,b))||(a.google_allow_expandable_ads=m);var d=!sc();pc&&d&&b.write("<"+c+' src="http://'+q+'/pagead/expansion_embed.js"></'+c+">");var e=tc(a,b,o("1",0.01)),f=d||e;f&&na("msie")&&!window.opera?b.write("<"+c+' src="http://'+q+'/pagead/render_ads.js"></'+c+">"):b.write("<"+c+">window.google_render_ad();</"+c+">")}function V(a){return a!=l?'"'+a+'"':'""'}function W(a,b){if(a&&b)window.google_ad_url+="&"+a+"="+b}
function X(a){var b=window,c=ka(a),d=b[a];W(c,d)}function Y(a,b){b!=l&&W(a,la(b))}function Z(a){var b=window,c=ka(a),d=b[a];Y(c,d)}function $(a,b){var c=window,d=ka(a),e=c[a];if(d&&e&&typeof e=="object")e=e[b%e.length];W(d,e)}
function uc(a){var b=a.screen,c=navigator.javaEnabled(),d=-(new Date).getTimezoneOffset();if(b){W("u_h",b.height);W("u_w",b.width);W("u_ah",b.availHeight);W("u_aw",b.availWidth);W("u_cd",b.colorDepth)}W("u_tz",d);W("u_his",history.length);W("u_java",c);navigator.plugins&&W("u_nplug",navigator.plugins.length);navigator.mimeTypes&&W("u_nmime",navigator.mimeTypes.length)}
function vc(a){if(a.google_enable_first_party_cookie){if(a._GA_googleCookieHelper==l)a._GA_googleCookieHelper=new w;if(!a._google_cookie_fetched){a._google_cookie_fetched=h;a._GA_googleCookieHelper.q(wc(a.google_ad_client))}}}function wc(a){if(a){a=a.toLowerCase();if(a.substring(0,3)!="ca-")a="ca-"+a}return a}function xc(a){if(a){a=a.toLowerCase();if(a.substring(0,9)!="dist-aff-")a="dist-aff-"+a}return a}function yc(a){var b="google_unique_id";if(a[b])++a[b];else a[b]=1;return a[b]}
function zc(){var a=M&&O("6"),b=rb&&O("1.8.1"),c=N&&O("525");if(xb&&(a||b||c))return h;else if(wb&&(c||b))return h;else if(yb&&b)return h;return m}function sc(){return(typeof ExpandableAdSlotFactory=="function"||typeof ExpandableAdSlotFactory=="object")&&typeof ExpandableAdSlotFactory.createIframe=="function"}function rc(a,b){if(a.google_allow_expandable_ads===m||!b.body||a.google_ad_output!="html"||Qa(a,b)||ra(a)||isNaN(a.google_ad_height)||isNaN(a.google_ad_width)||!zc())return m;return h}
function Ac(a,b){if((a.google_unique_id||0)==0&&a.google_ad_output=="html"&&document.body&&typeof b.body.getBoundingClientRect=="function")return s(["36812001","36812002"],o("0.01",0));return""}
function Bc(a,b){var c="";if((a.google_unique_id||0)==0&&(a.google_ad_output=="js"||a.google_ad_output=="html")){ra(a)||(c=s(["36813001","36813002","36813003","36813004"],o("0.008",0)));if(c=="")c=s(["36813005","36813006"],o("0.008",0));switch(c){case "36813002":b.c(1);b.d(["js"]);break;case "36813003":b.c(1);b.d(["html"]);break;case "36813004":b.c(2);b.d(["html","js"]);break;case "36813006":b.c(0);b.d(["html","js"]);break}}return c}
function Cc(a,b,c,d){var e=yc(a);c=c.substring(0,1992);c=c.replace(/%\w?$/,"");var f="script";if((a.google_ad_output=="js"||a.google_ad_output=="json_html")&&(a.google_ad_request_done||a.google_radlink_request_done))b.write("<"+f+' language="JavaScript1.1" src='+V(Dc(c))+"></"+f+">");else if(a.google_ad_output=="html")if(pc&&sc()){var j=a.google_container_id||d||l;a["google_expandable_ad_slot"+e]=ExpandableAdSlotFactory.createIframe("google_ads_frame"+e,Dc(c),a.google_ad_width,a.google_ad_height,
j)}else{var k='<iframe name="google_ads_frame" width='+V(a.google_ad_width)+" height="+V(a.google_ad_height)+" frameborder="+V(a.google_ad_frameborder)+" src="+V(Dc(c))+' marginwidth="0" marginheight="0" vspace="0" hspace="0" allowtransparency="true" scrolling="no"></iframe>';a.google_container_id?Ec(a.google_container_id,b,k):b.write(k)}else a.google_ad_output=="textlink"&&b.write("<"+f+' language="JavaScript1.1" src='+V(Dc(c))+"></"+f+">")}
function Fc(a,b,c){if(!a)return m;if(!b)return h;return c}function Gc(a){for(var b in ha)a[b]=l;for(b in ia)b=="google_correlator"||(a[b]=l);for(b in ja)a[b]=l;a.google_allow_expandable_ads=l;a.google_container_id=l;a.google_tag_info=l;a.google_eids=l}
function Hc(a,b){var c=l,d=window,e=document,f=n,j=d.google_ad_format,k=Ic(d),i;if(d.google_cpa_choice!=c){d.google_ad_url=k+"/cpa/ads?";i=escape(wc(d.google_ad_client));d.google_ad_region="_google_cpa_region_";X("google_cpa_choice");if(typeof e.characterSet!="undefined")Y("oe",e.characterSet);else typeof e.charset!="undefined"&&Y("oe",e.charset)}else if(r(j)){d.google_ad_url=k+"/pagead/sdo?";i=escape(xc(d.google_ad_client))}else{d.google_ad_url=k+"/pagead/ads?";i=escape(wc(d.google_ad_client))}d.google_ad_url+=
"client="+i;X("google_ad_host");X("google_ad_host_tier_id");var g=d.google_num_slots_by_client,z=d.google_num_slots_by_channel,u=d.google_prev_ad_formats_by_region,v=d.google_prev_ad_slotnames_by_region;if(d.google_ad_region==c&&d.google_ad_section!=c)d.google_ad_region=d.google_ad_section;var t=d.google_ad_region==c?"":d.google_ad_region;if(r(j)){d.google_num_sdo_slots=d.google_num_sdo_slots?d.google_num_sdo_slots+1:1;if(d.google_num_sdo_slots>4)return m}else if(qa(d)){d.google_num_0ad_slots=d.google_num_0ad_slots?
d.google_num_0ad_slots+1:1;if(d.google_num_0ad_slots>3)return m}else if(d.google_cpa_choice==c){d.google_num_ad_slots=d.google_num_ad_slots?d.google_num_ad_slots+1:1;if(d.google_num_slots_to_rotate){u[t]=c;v[t]=c;if(d.google_num_slot_to_show==c)d.google_num_slot_to_show=f%d.google_num_slots_to_rotate+1;if(d.google_num_slot_to_show!=d.google_num_ad_slots)return m}else if(d.google_num_ad_slots>6&&t=="")return m}W("dt",n);X("google_language");d.google_country?X("google_country"):X("google_gl");X("google_region");
Z("google_city");Z("google_hints");X("google_safe");X("google_encoding");X("google_last_modified_time");Z("google_alternate_ad_url");X("google_alternate_color");X("google_skip");X("google_targeting");var K=d.google_ad_client;if(g[K])g[K]+=1;else{g[K]=1;g.length+=1}if(u[t])if(!r(j)){Y("prev_fmts",u[t].toLowerCase());g.length>1&&W("slot",g[K])}v[t]&&Y("prev_slotnames",v[t].toLowerCase());if(Fc(j,d.google_ad_slot,d.google_override_format)){Y("format",j.toLowerCase());r(j)||(u[t]=u[t]?u[t]+","+j:j)}else if(d.google_ad_slot)v[t]=
v[t]?v[t]+","+d.google_ad_slot:d.google_ad_slot;X("google_max_num_ads");W("output",d.google_ad_output);X("google_adtest");X("google_ad_callback");X("google_ad_slot");Z("google_correlator");d.google_new_domain_checked==1&&d.google_new_domain_enabled==0&&W("dblk",1);if(d.google_ad_channel){Z("google_ad_channel");for(var lb="",nb=d.google_ad_channel.split(Jc),ua=0;ua<nb.length;ua++){var va=nb[ua];if(z[va])lb+=va+"+";else z[va]=1}Y("pv_ch",lb)}if(d.google_ad_host_channel){Z("google_ad_host_channel");
var Qc=Kc(d.google_ad_host_channel,d.google_viewed_host_channels);Y("pv_h_ch",Qc)}d.google_enable_first_party_cookie&&Y("cookie",d._GA_googleCookieHelper.v());Z("google_page_url");$("google_color_bg",f);$("google_color_text",f);$("google_color_link",f);$("google_color_url",f);$("google_color_border",f);$("google_color_line",f);d.google_reuse_colors?W("reuse_colors",1):W("reuse_colors",0);X("google_font_face");X("google_kw_type");Z("google_kw");Z("google_contents");X("google_num_radlinks");X("google_max_radlink_len");
X("google_rl_filtering");X("google_rl_mode");X("google_rt");Z("google_rl_dest_url");X("google_num_radlinks_per_unit");X("google_ad_type");X("google_image_size");X("google_ad_region");oc(d.google_eids);Y("eid",mc);var ob=d.google_allow_expandable_ads;if(ob!=l)ob?W("ea","1"):W("ea","0");X("google_feedback");Z("google_referrer_url");Z("google_page_location");W("frm",d.google_iframing);X("google_bid");X("google_ctr_threshold");X("google_cust_age");X("google_cust_gender");X("google_cust_interests");X("google_cust_id");
X("google_cust_job");X("google_cust_u_url");X("google_cust_l");X("google_cust_lh");X("google_cust_ch");X("google_ed");X("google_video_doc_id");X("google_video_product_type");Z("google_ui_features");Z("google_ui_version");Z("google_tag_info");Z("google_only_ads_with_video");Z("google_only_pyv_ads");Z("google_disable_video_autoplay");if(a){Y("dff",dc(a));Y("dfs",hc(a));var y;if(b)if(typeof a.getBoundingClientRect=="function"){var pb=a.getBoundingClientRect();y={x:pb.left,y:pb.top}}else{y={};y.x="-252738";
y.y="-252738"}else try{y=bc(a)}catch(cd){y={};y.x="-252738";y.y="-252738"}var wa=Hb(window);if(y&&wa){Y("biw",wa.width);Y("bih",wa.height);Y("adx",y.x);Y("ady",y.y)}}ic();W("ga_vid",d.gaGlobal.vid);W("ga_sid",d.gaGlobal.sid);W("ga_hid",d.gaGlobal.hid);W("ga_fc",d.gaGlobal.from_cookie);Z("google_analytics_uacct");X("google_ad_override");X("google_flash_version");W("w",d.google_ad_width||-1);W("h",d.google_ad_height||-1);uc(d);return h}
function Kc(a,b){for(var c=a.split("|"),d=-1,e=[],f=0;f<c.length;f++){var j=c[f].split(Jc);b[f]||(b[f]={});for(var k="",i=0;i<j.length;i++){var g=j[i];if(!(g==""))if(b[f][g])k+="+"+g;else b[f][g]=1}k=k.slice(1);e[f]=k;if(k!="")d=f}var z="";if(d>-1){for(f=0;f<d;f++)z+=e[f]+"|";z+=e[d]}return z}
function Lc(){var a=window,b=document;vc(a);var c=Oa(),d=s(["68120011","68120021","68120031","68120041"],o("0.04",0));if(d==""){d=Ac(a,b);if(d=="")d=Bc(a,c)}nc(d);var e,f=m,j=m,k=m;switch(d){case "68120031":k=h;case "68120021":j=h;case "68120041":f=h;break;case "36812002":if(!window.google_atf_included){window.google_atf_included=h;ma("http://"+q+"/pagead/atf.js")}break}if(f){var i="google_temp_span";e=a.google_container_id&&Eb(a.google_container_id)||Eb(i);if(!e&&!a.google_container_id){b.write("<span id="+
i+"></span>");e=Eb(i)}}var g=m;g=j?Hc(e,k):Hc();e&&e.id==i&&Nb(e);if(g){c.D(a.google_ad_output,a.google_ad_url);Cc(a,b,a.google_ad_url);Gc(a)}}function Dc(a){var b=(new Date).getTime()-n,c="&dtd="+(b<1000?b:"M");return a+c}function Mc(){Lc();return h}
function Nc(a){var b=window,c=l,d=b.onerror;b.onerror=a;if(b.google_ad_frameborder==c)b.google_ad_frameborder=0;if(b.google_ad_output==c)b.google_ad_output="html";if(r(b.google_ad_format)){var e=b.google_ad_format.match(/^(\d+)x(\d+)_.*/);if(e){b.google_ad_width=parseInt(e[1],10);b.google_ad_height=parseInt(e[2],10);b.google_ad_output="html"}}if(b.google_ad_format==c&&b.google_ad_output=="html")b.google_ad_format=b.google_ad_width+"x"+b.google_ad_height;Ya(b,document);if(b.google_num_slots_by_channel==
c)b.google_num_slots_by_channel=[];if(b.google_viewed_host_channels==c)b.google_viewed_host_channels=[];if(b.google_num_slots_by_client==c)b.google_num_slots_by_client=[];if(b.google_prev_ad_formats_by_region==c)b.google_prev_ad_formats_by_region=[];if(b.google_prev_ad_slotnames_by_region==c)b.google_prev_ad_slotnames_by_region=[];if(b.google_correlator==c)b.google_correlator=n;if(b.google_adslot_loaded==c)b.google_adslot_loaded={};if(b.google_adContentsBySlot==c)b.google_adContentsBySlot={};if(b.google_flash_version==
c)b.google_flash_version=pa();if(b.google_new_domain_checked==c)b.google_new_domain_checked=0;if(b.google_new_domain_enabled==c)b.google_new_domain_enabled=0;b.onerror=d}function Oc(a){for(var b={},c=a.split("?"),d=c[c.length-1].split("&"),e=0;e<d.length;e++){var f=d[e].split("=");if(f[0])try{b[f[0].toLowerCase()]=f.length>1?window.decodeURIComponent?decodeURIComponent(f[1].replace(/\+/g," ")):unescape(f[1]):""}catch(j){}}return b}
function Pc(){var a=window,b=Oc(document.URL);if(b.google_ad_override){a.google_ad_override=b.google_ad_override;a.google_adtest="on"}}function Ec(a,b,c){if(a){var d=b.getElementById(a);if(d&&c&&c.length!=""){d.style.visibility="visible";d.innerHTML=c}}}var Jc=/[+, ]/;window.google_render_ad=Lc;var Rc={google:1,googlegroups:1,gmail:1,googlemail:1,googleimages:1,googleprint:1};function Sc(a){var b=a.google_page_location||a.google_page_url;if(!b)return m;b=b.toString();if(b.indexOf("http://")==0)b=b.substring(7,b.length);else if(b.indexOf("https://")==0)b=b.substring(8,b.length);var c=b.indexOf("/");if(c==-1)c=b.length;var d=b.substring(0,c),e=d.split("."),f=m;if(e.length>=3)f=e[e.length-3]in Rc;if(e.length>=2)f=f||e[e.length-2]in Rc;return f}
function tc(a,b,c){if(Sc(a)){a.google_new_domain_checked=1;return m}if(a.google_new_domain_checked==0){var d=Math.random();if(d<=c){var e="http://"+ea+"/pagead/test_domain.js",f="script";b.write("<"+f+' src="'+e+'"></'+f+">");a.google_new_domain_checked=1;return h}}return m}function Ic(a){if(!Sc(a)&&a.google_new_domain_enabled==1)return"http://"+ea;return"http://"+fa};var Tc=["30143070","30143071","30143072","30143073","30143074","30143075"],Uc=typeof window.postMessage=="function"||typeof window.postMessage=="object"||typeof document.postMessage=="function",Wc=function(a,b){typeof A1_googleCreateSlot=="function"?A1_googleCreateSlot(a.google_ad_client):Vc(a,b)},Xc=function(){if(!(Uc||!N))return m;return h},Yc=function(a){if(ra(a))return m;var b=a.google_ad_output;if(b&&b!="html")return m;var c=a.google_ad_client;if(typeof c!="string"||c.substring(0,4)!="pub-"&&
c.substring(0,7)!="ca-pub-")return m;return h},$c=function(a){if(typeof a.google_a1_eid=="string")return a.google_a1_eid;var b=o("0.01",0);a.google_a1_eid=Zc(Tc,b);return a.google_a1_eid},Vc=function(a,b){if(!a.google_included_a1_script){var c="script",d="/pagead/show_ads_sra2.js";b.write("<"+c+' src="http://'+q+d+'"></'+c+">");a.google_included_a1_script=h}},Zc=function(a,b){var c=Math.random();if(c<b){var d=Math.floor(c/b*a.length);return a[d]}return""};function ad(){Pc();Nc(Mc);qc(window,document)}if(!Xc(window)||!Yc(window))ad();else{var bd=$c(window);if(bd){nc(bd);window.google_allow_expandable_ads=m}!bd||bd=="30143070"?ad():Wc(window,document)};
})()
