using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
namespace PimpLibrary.Static.Enums
{
    /// <summary>
    /// Summary description for CeTypeEnum
    /// </summary>
    public enum CeTypeEnum
    {
        destroyed,
        dragonFlownAway,
        cancelledrelations,
        hostilekingdom,
        peace,
        startwar,
        canceledCFProposal,
        warwin,
        stalemate,
        endhostile,
        endpeace,
        starthostile,
        degradedwar,
        learned,
        razed,
        pillaged,
        attemptedinvasion,
        captured,
        killed,
        ambushed,
        defectedfrom,
        provincedie,
        defectedto,
        collapsed,
        aid,
        declaredwar,
        ceasefire,
        brokenceasefire,
        withdrawn,
        surrendered,
        cancelledceasefire,
        rejectedceasefire,
        flightdragon,
        slaindragon,
        kingdombegundragon,
        dragontargetted,
        dragonravaginglands,
        cancelleddragon,
        endEarlyPostWar,
        startpeace,

        TheyDefectedToKingdom,
        DragonProjectStartedSapphire,
        TheyWithDrewFromWar,
        BrokenCeasefireAgreementWithUs,

        StartedGoldDragonProjectAgainstUs,
        StartedEmeraldDragonProjectAgainstUs,
        StartedSapphireDragonProjectAgainstUs,

        RubyDragonProjectAgainstUs,
        SlainDragonRavagingLands,
        TheyCancelledTheirDragonProjectTowardsUs,

        GoldDragonRavagingLands,
        RubyDragonRavagingLands,
        EmeraldDragonRavagingLands,
        SapphireDragonRavagingLands,

        WithDrawnOurCeasefireProposal,
       WithDrawnTheirCeasefireProposal,
       WithDrawnTheirPeaceOffer,
        WeRejectedTheirPeaceOffer,
        OurDragonSetFlight,
        WeDeclaredWar,
        TheyDeclaredWar,
        RazedProvince,
        RazedProvinceIntraKingdom,
        AidSent,
        Ambush,
        CaputeredLand,
        CaputeredLandIntraKingdom,
        CeProblem,
        DragonProjectStartedEmerald,
        DragonProjectStartedRuby,
        DragonProjectStartedGold,
        DragonRavagingLands,
        DragonFlownAway,
        //WarAction,
        //AttackOnSelf,
        ArmyReturns,
        TrackedProvinceUpdated,
        OpsEnding,
        AttemptedToInvade,
        AttemptedToInvadeIntraKingdom,
        AbandonedProvince,
        LeftKingdom,
        JoinedKingdom,
        Massacred,
        AttackedAndStole,
        CancelledCeasefireProposalWithOurKingdom,
        ProposedCeasefireWithOurKingdom,
        WeProposedCeasefire,
        WeCancelledCeasefire,
        EnteredFormalCeaseFire,
        AcceptedOurCeaseFireProposal,
        OurKingdomCancelledDragon,
        MonarchDestroyedProvince,
        OrderedEarlyEndToPostWar,
        TheyProposedMutualPeace,
        TheyProposedPeaceWithdrawn,

        CETypeCheckProblem,
        CETypeCheckCantFind
    }
}