using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace PimpLibrary.Utopia.Ops
{
    public enum OpType
    {
        warSpoils,
        pitfalls,
        MagesFury,
        Nightmares,
        assasinate,
        assasinateWizs,
        kidnapped,
        stoleMoney,
        riots,
        riotsNoEffects,
        bribed,
        bribedGen,
        sabotageSpells,
        stoleRunes,
        stoleFood,
        burnedAcres,
        triedToBurnAcres,
        stealHorses,
        freePrisoners,
        Infiltrated,
        minorProtection,
        fog,
        magicShield,
        fertileLands,
        aggression,
        naturesBlessing,
        highBirth,
        fastBuilders,
        inspireArmy,
        patriotism,
        reflectMagic,
        speedAttack,
        townWatch,
        clearSight,
        treeGold,
        anonymity,
        incineratesRunes,
        tornadoes,
        fireball,
        greedySoldiers,
        fountainKnowledge,
        goldToLead,
        goldToLeadNoEffects,
        exposedThieves,
        storms,
        stormsNoEffects,
        explosions,
        meteors,
        vermin,
        drought,
        droughtNoEffects,
        chastity,
        forgetBooks,
        landLust,
        convertThieves,
        convertedWizards,
        convertedTroops,
        convertedTroopsFailed,
        convertedSpecialists,
        wakeDead,
        shadowlight,
        paradise,
        naturesBlessingFailed,
        greatProtection,
        quickFeet,
        animateDead,
        mystVort,
        mystVortFailed,
        donatedGoldDragon,
        killingDragon,
        sentRunes,
        sentMoney,
        mysticAura,
        thievesInvisible,
        fanaticism,
        armySpeed,
        landShadowLight,
        NoRaiseDead,
        ProtectMagic,
        TroopStrength,
        plague,


    }
}
